unpackaged/main/default/objects/Account/fields/discount__c.field-meta.xml
<CustomField>
    <fullName>discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Скидка</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ShippingCountry__c.field-meta.xml
<CustomField>
    <fullName>ShippingCountry__c</fullName>
    <label>Страна (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Россия</fullName>
            </value>
            <value>
                <fullName>Беларусь</fullName>
            </value>
            <value>
                <fullName>Казахстан</fullName>
            </value>
            <value>
                <fullName>Украина</fullName>
            </value>
            <value>
                <fullName>Словакия</fullName>
            </value>
            <value>
                <fullName>Литва</fullName>
            </value>
            <value>
                <fullName>Монголия</fullName>
            </value>
            <value>
                <fullName>Австрия</fullName>
            </value>
            <value>
                <fullName>Приднестровская республика</fullName>
            </value>
            <value>
                <fullName>Узбекистан</fullName>
            </value>
            <value>
                <fullName>Молдавия</fullName>
            </value>
            <value>
                <fullName>Абхазия</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ShippingRegion__c.field-meta.xml
<CustomField>
    <fullName>ShippingRegion__c</fullName>
    <label>Область/Регион (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ShippingCountry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Республика Кабардино-Балкарская</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесская</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия — Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва (Тува)</fullName>
            </value>
            <value>
                <fullName>Республика Удмуртская</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Республика Чеченская</fullName>
            </value>
            <value>
                <fullName>Республика Чувашская</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Забайкальский край</fullName>
            </value>
            <value>
                <fullName>Камчатский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Пермский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
            <value>
                <fullName>Ставропольский край</fullName>
            </value>
            <value>
                <fullName>Хабаровский край</fullName>
            </value>
            <value>
                <fullName>Москва</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Организацию</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>mDVt</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/act__c/act__c.object-meta.xml
<CustomObject>
    <label>Акт шеф-монтажа</label>
    <nameField>
        <displayFormat>{000}/{MM}.{YY}</displayFormat>
        <label>Номер акта</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Акты шеф-монтажа</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/act__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Акты шеф-монтажа</relationshipLabel>
    <relationshipName>Act</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/act__c/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Акт</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Акты шеф-монтажа</relationshipLabel>
    <relationshipName>mDWm</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Проект (Сделка)</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Оборудование на объекте</relationshipLabel>
    <relationshipName>activeOpp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Оборудование</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Активы</relationshipLabel>
    <relationshipName>mDWc</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Обращения</relationshipLabel>
    <relationshipName>opp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Обращение</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Обращения</relationshipLabel>
    <relationshipName>mDW8</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/StartWorkingProducts__c.field-meta.xml
<CustomField>
    <fullName>StartWorkingProducts__c</fullName>
    <label>Дата ввода оборудования в эксплуатацию</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник ответственный за Проект</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Возможности</relationshipLabel>
    <relationshipName>mExE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroup__c/OpportunityGroup__c.object-meta.xml
<CustomObject>
    <label>Группа проекта</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Идентификатор</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Группа проекта</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OpportunityGroup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>OppGroup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroup__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <label>Роль</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Менеджер по продажам</fullName>
            </value>
            <value>
                <fullName>Региональный менеджер по продажам</fullName>
            </value>
            <value>
                <fullName>Руководитель отдела продаж</fullName>
            </value>
            <value>
                <fullName>Руководитель сервисной службы</fullName>
            </value>
            <value>
                <fullName>Сервисный инженер</fullName>
            </value>
            <value>
                <fullName>Проектировщик</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityGroup__c/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник</label>
    <referenceTo>User__c</referenceTo>
    <relationshipName>UserTION</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/ProjectMember__c.object-meta.xml
<CustomObject>
    <label>Контрагент</label>
    <nameField>
        <displayFormat>ProjectMember-{0}</displayFormat>
        <label>Код контрагента</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Контрагенты</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProjectMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Организация</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Проекты (участник)</relationshipLabel>
    <relationshipName>Project_membersWMZ8</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <label>Проект</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Контрагенты</relationshipLabel>
    <relationshipName>Project_memberHUKx</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/fields/ProjectRoles__c.field-meta.xml
<CustomField>
    <fullName>ProjectRoles__c</fullName>
    <label>Роли в проекте</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Генпроектировщик</fullName>
            </value>
            <value>
                <fullName>Субпроектировщик</fullName>
            </value>
            <value>
                <fullName>Генподрядчик</fullName>
            </value>
            <value>
                <fullName>Субподрядчик</fullName>
            </value>
            <value>
                <fullName>Эксплуатация</fullName>
            </value>
            <value>
                <fullName>Заказчик</fullName>
            </value>
            <value>
                <fullName>Дилер</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Процент скидки</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Смету</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Сметы</relationshipLabel>
    <relationshipName>mDWD</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>Пользователь ТИОН</label>
    <nameField>
        <label>ФИО</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Пользователи ТИОН</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Профиль пользователя</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCustom</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestOpportunity.cls
@isTest(seeAllData=true)
private class TestOpportunity {  
    static testMethod void TestStageByBusinessProcess() {            
        BusinessProcess bp1 = [SELECT id FROM BusinessProcess WHERE Name = 'Тион, продажа О2 дилерам'];
        BusinessProcess bp2 = [SELECT id FROM BusinessProcess WHERE Name = 'Тион, выбивание конкурентов'];
        BusinessProcess bp3 = [SELECT id FROM BusinessProcess WHERE Name = 'Тион, базовый процесс продаж'];
        StageByBusinessProcess sbp = new StageByBusinessProcess();
        system.assertEquals(sbp.getNextStage(bp1, 'Холодный звонок'), 'Переговоры (обсуждение условий)');
        system.assertEquals(sbp.getNextStage(bp2, 'Отслеживание конкурса на монтаж'),'Конкурс на монтаж завершен');
        system.assertEquals(sbp.getNextStage(bp3, 'Отслеживание конкурса на монтаж'),'Конкурс на монтаж завершен');
        system.assertEquals(sbp.getNextStage(bp3, ''),'Отслеживание конкурса на проектирование');
    }      
    
    
    static testMethod void TestLookup() {
        PageReference pageRef = Page.ContractorCustomLookup;
        Account account = new Account(Name='Test acc',
                                      Type='Монтажник',
                                      Phone='1234',
                                      ShippingCountry__c='Россия',
                                      ShippingRegion__c='Москва');
        insert account;
        Opportunity opp = new Opportunity(Name='Test opp',StageName='Подбор оборудования',CloseDate=Date.today());
        BusinessProcess bp = [SELECT Id FROM BusinessProcess WHERE Name = 'Тион, продажа О2 дилерам'];
        RecordType rt = [SELECT Id FROM RecordType WHERE BusinessProcessId = :bp.ID limit 1];
        opp.RecordTypeId = rt.Id;
        insert opp;
        pageRef.getParameters().put('accountId',account.Id);
        pageRef.getParameters().put('oppId',opp.Id);
        pageRef.getParameters().put('retURL','www.tion.info');
        pageRef.getParameters().put('saveURL','www.tion.info');
        Test.setCurrentPageReference(pageRef);
        ContractorLookupController controller = new ContractorLookupController();  
        controller.contractor.ProjectRoles__c = 'Дилер';
        controller.save();          
        controller.cancel();
        ProjectMember__c contractor = controller.getContractor();
        System.debug('Current contractor: ' + contractor.Id);
        
    }
    
    static testMethod void TestAct() {
        PageReference pageRef = Page.ActPDF;
        Test.setCurrentPageReference(pageRef);    
        Opportunity opp = [SELECT id FROM opportunity Where OwnerId = :userinfo.getUserID() limit 1 offset 2];        
        opp.StartWorkingProducts__c = date.newinstance(2013, 2, 17);
        update opp;
        act__c act = new act__c(Opportunity__c = opp.id);
        insert act;
        ApexPages.StandardController sc = new ApexPages.StandardController(act);
        ActExtensionController controller = new ActExtensionController(sc);      
        controller.getStartDate();
        controller.getStartDateMin();
        controller.getCountAssets();
        controller.getAssetList();
        
    }
    
    
    static testMethod void testTriggerProjectAdd(){
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        Pricebook2 pb2 = new Pricebook2(Name = 'test');
        insert pb2;
        Account account = new Account(Name='Test acc',
                                      Type='Монтажник',
                                      Phone='1234',
                                      ShippingCountry__c='Россия',
                                      ShippingRegion__c='Москва', discount__c = 20);
        insert account;  
        Opportunity opportunity = new Opportunity(Name='Test opp',StageName='Закупка оборудования',CloseDate=Date.today(), Pricebook2Id = pb2.Id);
        BusinessProcess bp = [SELECT Id FROM BusinessProcess WHERE Name = 'Тион, продажа О2 дилерам'];
        RecordType rt = [SELECT Id FROM RecordType WHERE BusinessProcessId = :bp.ID limit 1];
        opportunity.RecordTypeId = rt.Id;
        opportunity.accountId = account.Id;
        insert opportunity;                
        ProjectMember__c contractor = new ProjectMember__c(AccountId__c = account.Id,OpportunityId__c = opportunity.Id, ProjectRoles__c = 'Дилер');
        insert contractor;
        Product2 p2 = new Product2(Name = 'Компактная вентиляционная система Тион О2');
        insert p2;
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = p2.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice;
        PricebookEntry pe = new PricebookEntry(UnitPrice = 100, IsActive = true, Product2Id = p2.Id, Pricebook2Id = pb2.Id);
        insert pe;
        OpportunityLineItem oln = new OpportunityLineItem(OpportunityId = Opportunity.Id, PricebookEntryId = pe.Id, Quantity = 1, UnitPrice = 100);
        insert oln;
        
        contractor.ProjectRoles__c = 'Генподрядчик';
        update contractor;
        
        List<Opportunity> opplist = [SELECT id FROM opportunity Where OwnerId = :userinfo.getUserID() limit 2];
        opportunity = opplist[1];
        bp = [SELECT Id FROM BusinessProcess WHERE Name = 'Тион, базовый процесс продаж'];
        rt = [SELECT Id FROM RecordType WHERE BusinessProcessId = :bp.ID limit 1];
        opportunity.RecordTypeId = rt.Id;  
        opportunity.StageName='Подбор оборудования';
        update opportunity;
        
        try{
            p2 = new Product2(Name = 'ТИОН МЕД');
            insert p2;
            standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = p2.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
            insert standardPrice;
            pe = new PricebookEntry(UnitPrice = 100, IsActive = true, Product2Id = p2.Id, Pricebook2Id = pb2.Id);
            insert pe;
            oln = new OpportunityLineItem(OpportunityId = Opportunity.Id, PricebookEntryId = pe.Id, Quantity = 1, UnitPrice = 100);
            insert oln;
            
            p2 = new Product2(Name = 'ТИОН ПРОМ');
            insert p2;
            standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = p2.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
            insert standardPrice;
            pe = new PricebookEntry(UnitPrice = 100, IsActive = true, Product2Id = p2.Id, Pricebook2Id = pb2.Id);
            insert pe;
            oln = new OpportunityLineItem(OpportunityId = Opportunity.Id, PricebookEntryId = pe.Id, Quantity = 1, UnitPrice = 100);
            insert oln;
        }catch(System.DMLException e) {                
        }
    }
    
    static testMethod void TestOppGroup() {
        PageReference pageRef = Page.OpportunityGroupAdd;
        Account account = new Account(Name='Test acc',
                                      Type='Монтажник',
                                      Phone='1234',
                                      ShippingCountry__c='Россия',
                                      ShippingRegion__c='Москва');
        insert account;
        Opportunity opp = new Opportunity(Name='Test opp',StageName='Подбор оборудования',CloseDate=Date.today());
        BusinessProcess bp = [SELECT Id FROM BusinessProcess WHERE Name = 'Тион, продажа О2 дилерам'];
        RecordType rt = [SELECT Id FROM RecordType WHERE BusinessProcessId = :bp.ID limit 1];
        opp.RecordTypeId = rt.Id;
        insert opp;
        pageRef.getParameters().put('accountId',account.Id);
        pageRef.getParameters().put('oppId',opp.Id);
        Test.setCurrentPageReference(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(new OpportunityGroup__c(Opportunity__c = opp.id));
        OpportunityGroupController controller = new OpportunityGroupController(sc);    
        Profile profile = [select id, Name from profile where Name = 'Менеджер по продажам'];    
        User user = new User(alias = 'tt03', email='testtest03@test.com', emailencodingkey='UTF-8', lastname='Менеджер по продажам', languagelocalekey='en_US', localesidkey='en_US', profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='testtest03@test.com');  
        insert user;  
        
        User__c UT = new User__c(User__c = User.Id, Name = 'Менеджер по продажам');
        insert UT;
        controller.ogc.UserTION__c=UT.Id;
        controller.ogc.UserRole__c='Менеджер по продажам';
        controller.ogc.Opportunity__c = opp.Id;
        controller.sendNotification = true;
        controller.saveForm();
        System.RunAs(user){  
            controller.saveForm();
        }
        controller.getItems();         
        controller.delForm();
        controller.userDel = UT.Id;
        controller.getDynamicForm();
        controller.getSetOwnerForm();
        controller.setOwnerForm();
        controller.getDeleteForm();           
        controller.delForm();
        
    }
    
    static testMethod void testCaseInsert(){
        Account account = new Account(Name='Test acc',
                                      Type='Монтажник',
                                      Phone='1234',
                                      ShippingCountry__c='Россия',
                                      ShippingRegion__c='Москва');
        insert account;  
        Opportunity opportunity = new Opportunity(Name='Test opp',StageName='Закупка оборудования',CloseDate=Date.today());
        BusinessProcess bp = [SELECT Id FROM BusinessProcess WHERE Name = 'Тион, продажа О2 дилерам'];
        RecordType rt = [SELECT Id FROM RecordType WHERE BusinessProcessId = :bp.ID limit 1];
        opportunity.RecordTypeId = rt.Id;
        insert opportunity; 
        asset a = new asset(Opportunity__c = opportunity.id, Name='111', accountId = account.Id);
        insert a;
        case c = new Case(AssetId = a.id);
        insert c;
    }
    
    static testMethod void QuoteDelItem(){
        Quote  q = [SELECT Id FROM Quote Limit 1];
        delete q;
    }
}