unpackaged/main/default/objects/Account/fields/discount__c.field-meta.xml
<CustomField>
    <fullName>discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Скидка</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/ProjectMember__c.object-meta.xml
<CustomObject>
    <label>Контрагент</label>
    <nameField>
        <displayFormat>ProjectMember-{0}</displayFormat>
        <label>Код контрагента</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Контрагенты</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProjectMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Организация</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Проекты (участник)</relationshipLabel>
    <relationshipName>Project_membersWMZ8</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <label>Проект</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Контрагенты</relationshipLabel>
    <relationshipName>Project_memberHUKx</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/fields/ProjectRoles__c.field-meta.xml
<CustomField>
    <fullName>ProjectRoles__c</fullName>
    <label>Роли в проекте</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Генпроектировщик</fullName>
            </value>
            <value>
                <fullName>Субпроектировщик</fullName>
            </value>
            <value>
                <fullName>Генподрядчик</fullName>
            </value>
            <value>
                <fullName>Субподрядчик</fullName>
            </value>
            <value>
                <fullName>Эксплуатация</fullName>
            </value>
            <value>
                <fullName>Заказчик</fullName>
            </value>
            <value>
                <fullName>Дилер</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ContractorLookupController.cls
public with sharing class ContractorLookupController {
    
    public final ProjectMember__c contractor;
    
    public ContractorLookupController() {
        Id accountId = ApexPages.currentPage().getParameters().get('accountId');
        Id oppId = ApexPages.currentPage().getParameters().get('oppId');
        contractor = new ProjectMember__c(AccountId__c = accountId, OpportunityId__c = oppId);
        
    }
    
    public ProjectMember__c getContractor() {
        return contractor;
    }
    
    
    public PageReference cancel() {
        return new PageReference(ApexPages.currentPage().getParameters().get('retURL'));
    }


    public PageReference save() {
                  
        Opportunity opp = [SELECT RecordTypeId FROM Opportunity WHERE id = :contractor.OpportunityId__c];
        BusinessProcess bp = [Select id, Name From BusinessProcess WHERE id in (SELECT BusinessProcessId FROM RecordType WHERE Id =: opp.RecordTypeId ) limit 1];
        if(((bp.name == 'Тион, продажа О2 дилерам' || bp.name == 'Сделка') && contractor.ProjectRoles__c.toUpperCase() != 'ДИЛЕР') || ((bp.name == 'Тион, продажа О2 дилерам' || bp.name == 'Сделка') && contractor.ProjectRoles__c.toUpperCase().indexOf('ДИЛЕР', 0) >= 0)){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,' Тип “Дилер” может быть добавлен только к типу возможности “Продажа Тион О2 дилерам” и с такой ролью в возможности может быть только одна организация. Добавление организаций с другими ролями к типу возможности “Продажа Тион О2 дилерам” запрещено'));
            return null;
        }
        if(bp.name == 'Тион, продажа О2 дилерам'){
            List<ProjectMember__c> ProjectMember = [SELECT AccountId__c FROM ProjectMember__c WHERE OpportunityId__c = :contractor.OpportunityId__c];
            if(ProjectMember.size() > 0){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'К проекту уже добавлена организация с ролью Дилер - можно добавить только одну организацию с такой ролью.'));
                return null;
            }
        }
        insert contractor;
        if(bp.name == 'Тион, продажа О2 дилерам'){             
            Account acc = [SELECT discount__c FROM Account WHERE Id = :contractor.AccountId__c];
            for (OpportunityLineItem o : [select Discount from OpportunityLineItem where OpportunityId = :contractor.OpportunityId__c]) {   
                o.Discount = acc.discount__c;
                update o;
            }
        }
        
        return new PageReference(ApexPages.currentPage().getParameters().get('saveURL'));
    }
    
   
}