unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Электронная почта</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ShippingCountry__c.field-meta.xml
<CustomField>
    <fullName>ShippingCountry__c</fullName>
    <label>Страна (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Россия</fullName>
            </value>
            <value>
                <fullName>Беларусь</fullName>
            </value>
            <value>
                <fullName>Казахстан</fullName>
            </value>
            <value>
                <fullName>Украина</fullName>
            </value>
            <value>
                <fullName>Словакия</fullName>
            </value>
            <value>
                <fullName>Литва</fullName>
            </value>
            <value>
                <fullName>Монголия</fullName>
            </value>
            <value>
                <fullName>Австрия</fullName>
            </value>
            <value>
                <fullName>Приднестровская республика</fullName>
            </value>
            <value>
                <fullName>Узбекистан</fullName>
            </value>
            <value>
                <fullName>Молдавия</fullName>
            </value>
            <value>
                <fullName>Абхазия</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ShippingRegion__c.field-meta.xml
<CustomField>
    <fullName>ShippingRegion__c</fullName>
    <label>Область/Регион (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ShippingCountry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Республика Кабардино-Балкарская</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесская</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия — Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва (Тува)</fullName>
            </value>
            <value>
                <fullName>Республика Удмуртская</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Республика Чеченская</fullName>
            </value>
            <value>
                <fullName>Республика Чувашская</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Забайкальский край</fullName>
            </value>
            <value>
                <fullName>Камчатский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Пермский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
            <value>
                <fullName>Ставропольский край</fullName>
            </value>
            <value>
                <fullName>Хабаровский край</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Организацию</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>mDVt</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Контакт</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Контакты</relationshipLabel>
    <relationshipName>mDW3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/AccountBillingName__c.field-meta.xml
<CustomField>
    <fullName>AccountBillingName__c</fullName>
    <inlineHelpText>Например, &quot;Общество с ограниченной ответственностью «Бегемот»&quot;</inlineHelpText>
    <label>Юридическое имя контрагента (полностью)</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/AccountCEO__c.field-meta.xml
<CustomField>
    <fullName>AccountCEO__c</fullName>
    <inlineHelpText>Например, в лице &quot;генерального директора Обломова Ильи Ильича&quot;</inlineHelpText>
    <label>В лице</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/AccountCEOAct__c.field-meta.xml
<CustomField>
    <fullName>AccountCEOAct__c</fullName>
    <defaultValue>&quot;Устава&quot;</defaultValue>
    <inlineHelpText>Например, &quot;Устава&quot;</inlineHelpText>
    <label>Действующего на основании</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/CompanyDeliverTo__c.field-meta.xml
<CustomField>
    <fullName>CompanyDeliverTo__c</fullName>
    <label>Грузополучатель</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>ContractNumber__c</fullName>
    <inlineHelpText>Первая буква - название нашего юрлица, затем вторая буква (без пробелов) - первая буква названия юрлица контрагента, затем, без пробелов, слеш и дата подписания договора</inlineHelpText>
    <label>Номер договора</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/DeliveryDuration__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDuration__c</fullName>
    <inlineHelpText>Указывается либо количество дней, либо дата поставки в формате «__»____________20__г.</inlineHelpText>
    <label>Срок поставки</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Partpayment__c.field-meta.xml
<CustomField>
    <fullName>Partpayment__c</fullName>
    <label>Оплата при готовности оборудования</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Partpayment_days__c.field-meta.xml
<CustomField>
    <fullName>Partpayment_days__c</fullName>
    <label>Срок при готовности оборудования (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/PostPayment__c.field-meta.xml
<CustomField>
    <fullName>PostPayment__c</fullName>
    <label>Оплата после отгрузки (процент)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Postpayment_days__c.field-meta.xml
<CustomField>
    <fullName>Postpayment_days__c</fullName>
    <label>Срок оплаты после отгрузки (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Prepayment__c.field-meta.xml
<CustomField>
    <fullName>Prepayment__c</fullName>
    <defaultValue>50</defaultValue>
    <label>Размер предоплаты (процент)</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Prepayment_days__c.field-meta.xml
<CustomField>
    <fullName>Prepayment_days__c</fullName>
    <label>Срок предоплаты (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Проект</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Договоры</relationshipLabel>
    <relationshipName>ProjectNameForContract</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SignatureInitials__c.field-meta.xml
<CustomField>
    <fullName>SignatureInitials__c</fullName>
    <inlineHelpText>Например, &quot;И.И. Обломов&quot;</inlineHelpText>
    <label>Инициалы и фамилия подписывающего лица</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Smeta__c.field-meta.xml
<CustomField>
    <fullName>Smeta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Смета</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Opportunity.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ProjectName__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Контракты</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SpecificationDate__c.field-meta.xml
<CustomField>
    <fullName>SpecificationDate__c</fullName>
    <label>Дата создания спецификации</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Договор</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Контракты</relationshipLabel>
    <relationshipName>mDWI</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник ответственный за Проект</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Возможности</relationshipLabel>
    <relationshipName>mExE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Организация</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Сметы</relationshipLabel>
    <relationshipName>OrganisationQuotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Смету</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Сметы</relationshipLabel>
    <relationshipName>mDWD</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>Пользователь ТИОН</label>
    <nameField>
        <label>ФИО</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Пользователи ТИОН</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Профиль пользователя</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCustom</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestDailyReportSender.cls
@isTest(SeeAllData=true)
private class TestDailyReportSender {

    static testMethod void testReportSending() {
        User__c user = new User__c(Name = 'Test user', Email__c='test@tion.info', User__c =UserInfo.getUserId() );
        insert user;
        DailyReportSender drs = new DailyReportSender();
        List<SelectOption> tionUsers = drs.tionUsers;
        drs.selectedUserId = (String) user.Id;
        //User__c user = [select Id, Name,Email__c from User__c where Id=:UserInfo.getUserId()];
        Account acc = new Account(Name='Организация',
                                Type='Proektirovwik',
                                Phone='1234',
                                ShippingCountry__c='Rossia',
                                ShippingRegion__c='Msk');
        insert acc;
        Contact contact = new Contact(LastName = 'familia',AccountId=acc.Id);
        insert contact;
        Task t1 = new Task(Subject = 'Task subject',
                            Type = 'Входящий вызов',
                            ActivityDate = Date.today(),
                            WhoId = contact.Id,
                            Description = 'описание',
                            TionOwner__c = 'Test user');
        Event e1 = new Event(Subject = 'Event subject',
                            Type = 'Event type',
                            ActivityDateTime = DateTime.now(),
                            DurationInMinutes = 15,
                            WhoId = contact.Id,
                            Description = 'Event description',
                            TionOwner__c = 'Test user');
        Task t2 = new Task(Subject = 'Task subject',
                            Type = 'Входящий вызов',
                            ActivityDate = Date.today(),
                            WhoId = contact.Id,
                            Description = 'описание',
                            TionOwner__c = 'Test user');
        Event e2 = new Event(Subject = 'Event subject',
                            Type = 'Event type',
                            ActivityDateTime = DateTime.now(),
                            DurationInMinutes = 15,
                            WhoId = contact.Id,
                            Description = 'Event description',
                            TionOwner__c = 'Test user');
        User__c UT = new User__c(User__c = UserInfo.getUserId(), Name = 'tester');
        insert UT;
        Opportunity opportunity = new Opportunity(Name='Test opp',StageName='test',CloseDate=Date.today(), UserTION__c = UT.id);
        insert opportunity;
        Quote quote = new Quote(Name = 'test', OpportunityId = opportunity.Id, Organisation__c = acc.id);
        insert quote;
        Contract contract = new Contract(AccountId=acc.Id,StartDate=Date.today(),ContractTerm=24);
        contract.Prepayment_days__c = 5;
        contract.Partpayment_days__c = 5;
        contract.Postpayment_days__c = 5;              
        contract.ProjectName__c = opportunity.Id;
        contract.Smeta__c = quote.Id;
        contract.AccountCEO__c = 'test';
        contract.AccountBillingName__c = 'test';
        contract.AccountCEOAct__c = 'test';
        contract.SignatureInitials__c = 'test';
        contract.SpecificationDate__c = Date.valueOf('2013-04-10'); 
        contract.CompanyDeliverTo__c = 'test';
        contract.DeliveryDuration__c = 'test';
        contract.Partpayment__c = 30;
        contract.Postpayment__c = 30;
        contract.Prepayment__c = 40;
        contract.ContractNumber__c = 'TT/11112022';
        insert contract;
        t1.WhatId = contract.Id;
        e1.WhatId = contract.Id;
        insert t1;
        insert e1;
        t2.WhatId = acc.Id;
        e2.WhatId = acc.Id;
        insert t2;
        insert e2;
        drs.setUserID(user.Id);
        drs.startSend();
        drs.startSend();
        drs.startSend();
        drs.startSend();
        drs.startSend();
        drs.startSend();
        drs.getStringCounts();
        drs.gethtml(); 
    }
}