unpackaged/main/default/objects/Account/fields/ShippingCountry__c.field-meta.xml
<CustomField>
    <fullName>ShippingCountry__c</fullName>
    <label>Страна (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Россия</fullName>
            </value>
            <value>
                <fullName>Беларусь</fullName>
            </value>
            <value>
                <fullName>Казахстан</fullName>
            </value>
            <value>
                <fullName>Украина</fullName>
            </value>
            <value>
                <fullName>Словакия</fullName>
            </value>
            <value>
                <fullName>Литва</fullName>
            </value>
            <value>
                <fullName>Монголия</fullName>
            </value>
            <value>
                <fullName>Австрия</fullName>
            </value>
            <value>
                <fullName>Приднестровская республика</fullName>
            </value>
            <value>
                <fullName>Узбекистан</fullName>
            </value>
            <value>
                <fullName>Молдавия</fullName>
            </value>
            <value>
                <fullName>Абхазия</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ShippingRegion__c.field-meta.xml
<CustomField>
    <fullName>ShippingRegion__c</fullName>
    <label>Область/Регион (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ShippingCountry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Республика Кабардино-Балкарская</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесская</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия — Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва (Тува)</fullName>
            </value>
            <value>
                <fullName>Республика Удмуртская</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Республика Чеченская</fullName>
            </value>
            <value>
                <fullName>Республика Чувашская</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Забайкальский край</fullName>
            </value>
            <value>
                <fullName>Камчатский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Пермский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
            <value>
                <fullName>Ставропольский край</fullName>
            </value>
            <value>
                <fullName>Хабаровский край</fullName>
            </value>
            <value>
                <fullName>Москва</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Организацию</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>mDVt</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/AccountBillingName__c.field-meta.xml
<CustomField>
    <fullName>AccountBillingName__c</fullName>
    <inlineHelpText>Например, &quot;Общество с ограниченной ответственностью «Бегемот»&quot;</inlineHelpText>
    <label>Юридическое имя контрагента (полностью)</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/AccountCEO__c.field-meta.xml
<CustomField>
    <fullName>AccountCEO__c</fullName>
    <inlineHelpText>Например, в лице &quot;генерального директора Обломова Ильи Ильича&quot;</inlineHelpText>
    <label>В лице</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/AccountCEOAct__c.field-meta.xml
<CustomField>
    <fullName>AccountCEOAct__c</fullName>
    <defaultValue>&quot;Устава&quot;</defaultValue>
    <inlineHelpText>Например, &quot;Устава&quot;</inlineHelpText>
    <label>Действующего на основании</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/CompanyDeliverTo__c.field-meta.xml
<CustomField>
    <fullName>CompanyDeliverTo__c</fullName>
    <label>Грузополучатель</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/DeliveryDuration__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDuration__c</fullName>
    <inlineHelpText>Указывается либо количество дней, либо дата поставки в формате «__»____________20__г.</inlineHelpText>
    <label>Срок поставки</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Partpayment__c.field-meta.xml
<CustomField>
    <fullName>Partpayment__c</fullName>
    <label>Оплата при готовности оборудования</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Partpayment_days__c.field-meta.xml
<CustomField>
    <fullName>Partpayment_days__c</fullName>
    <label>Срок при готовности оборудования (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/PostPayment__c.field-meta.xml
<CustomField>
    <fullName>PostPayment__c</fullName>
    <label>Оплата после отгрузки (процент)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Postpayment_days__c.field-meta.xml
<CustomField>
    <fullName>Postpayment_days__c</fullName>
    <label>Срок оплаты после отгрузки (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Prepayment_days__c.field-meta.xml
<CustomField>
    <fullName>Prepayment_days__c</fullName>
    <label>Срок предоплаты (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Проект</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Договоры</relationshipLabel>
    <relationshipName>ProjectNameForContract</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SignatureInitials__c.field-meta.xml
<CustomField>
    <fullName>SignatureInitials__c</fullName>
    <inlineHelpText>Например, &quot;И.И. Обломов&quot;</inlineHelpText>
    <label>Инициалы и фамилия подписывающего лица</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Smeta__c.field-meta.xml
<CustomField>
    <fullName>Smeta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Смета</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Opportunity.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ProjectName__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Контракты</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SpecificationDate__c.field-meta.xml
<CustomField>
    <fullName>SpecificationDate__c</fullName>
    <label>Дата создания спецификации</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Договор</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Контракты</relationshipLabel>
    <relationshipName>mDWI</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник ответственный за Проект</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Возможности</relationshipLabel>
    <relationshipName>mExE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Организация</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Сметы</relationshipLabel>
    <relationshipName>OrganisationQuotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Смету</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Сметы</relationshipLabel>
    <relationshipName>mDWD</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <label>Спецификация</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Спецификация</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Спецификации</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Specification__c/fields/CompanyDeliverTo__c.field-meta.xml
<CustomField>
    <fullName>CompanyDeliverTo__c</fullName>
    <label>Грузополучатель</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/fields/DeliveryDuration__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDuration__c</fullName>
    <inlineHelpText>Указывается либо количество дней, либо дата поставки в формате «__»____________20__г.</inlineHelpText>
    <label>Срок поставки</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/fields/Partpayment__c.field-meta.xml
<CustomField>
    <fullName>Partpayment__c</fullName>
    <label>Оплата при готовности оборудования</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/fields/Partpayment_days__c.field-meta.xml
<CustomField>
    <fullName>Partpayment_days__c</fullName>
    <label>Срок при готовности оборудования (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/fields/PostPayment__c.field-meta.xml
<CustomField>
    <fullName>PostPayment__c</fullName>
    <label>Оплата после отгрузки (процент)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/fields/Postpayment_days__c.field-meta.xml
<CustomField>
    <fullName>Postpayment_days__c</fullName>
    <label>Срок оплаты после отгрузки (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/fields/Prepayment_days__c.field-meta.xml
<CustomField>
    <fullName>Prepayment_days__c</fullName>
    <label>Срок предоплаты (дней)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/fields/SpecificationDate__c.field-meta.xml
<CustomField>
    <fullName>SpecificationDate__c</fullName>
    <label>Дата создания спецификации</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Specification__c/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник, ответственный за договор</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Спецификации</relationshipLabel>
    <relationshipName>J9mS</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>Пользователь ТИОН</label>
    <nameField>
        <label>ФИО</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Пользователи ТИОН</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Профиль пользователя</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCustom</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestContractExtensionController.cls
@isTest(seeAllData=true)
private class TestContractExtensionController {  
      static testMethod void Test1() {  
           Profile profile = [select id, Name from profile where Name = 'Менеджер по продажам'];    
           Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
           User user = new User(alias = 'tt02', email='testtest02@test.com', emailencodingkey='UTF-8', lastname='Менеджер по продажам', languagelocalekey='en_US', localesidkey='en_US', profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='testtest02@test.com');  
           insert user;  
           System.RunAs(user){  
               PageReference pageRef = Page.ContractPDF;
               Test.setCurrentPageReference(pageRef);
               Account account = new Account(Name='Test acc',
                                        Type='Монтажник',
                                        Phone='1234',
                                        ShippingCountry__c='Россия',
                                        ShippingRegion__c='Москва');
               insert account;               
               Pricebook2 pb2 = new Pricebook2(Name = 'test');
               insert pb2;
                User__c UT = new User__c(User__c = UserInfo.getUserId(), Name = 'Менеджер по продажам');
                insert UT;
               Opportunity opportunity = new Opportunity(Name='Test opp',StageName='test',CloseDate=Date.today(), Pricebook2Id = pb2.Id, UserTION__c = UT.id);
               insert opportunity;
               Quote quote = new Quote(Name = 'test', OpportunityId = opportunity.Id, Organisation__c = account.id, Pricebook2Id = pb2.Id);
               insert quote;                 
               Product2 p2 = new Product2(Name = 'test1 Пром');
               insert p2;
               PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = p2.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
               insert standardPrice;
               PricebookEntry pe = new PricebookEntry(UnitPrice = 100, IsActive = true, Product2Id = p2.Id, Pricebook2Id = pb2.Id);
               insert pe;
               QuoteLineItem qln = new QuoteLineItem(quoteId = quote.Id, PricebookEntryId = pe.Id, Quantity = 1, UnitPrice = 100);
               insert qln;
               OpportunityLineItem oln = new OpportunityLineItem(OpportunityId = Opportunity.Id, PricebookEntryId = pe.Id, Quantity = 1, UnitPrice = 100);
               insert oln;
               
               
               Contract cn = new Contract();
               cn.Prepayment_days__c = 5;
               cn.Partpayment_days__c = 5;
               cn.Postpayment_days__c = 5;              
               cn.ProjectName__c = opportunity.Id;
               cn.Smeta__c = quote.Id;
               cn.AccountId = account.Id;
               cn.AccountCEO__c = 'test';
               cn.AccountBillingName__c = 'test';
               cn.AccountCEOAct__c = 'test';
               cn.SignatureInitials__c = 'test';
               cn.SpecificationDate__c = Date.valueOf('2013-04-10'); 
               cn.StartDate =  Date.valueOf('2013-04-10');
               cn.CompanyDeliverTo__c = 'test';
               cn.DeliveryDuration__c = 'test';
               cn.Partpayment__c = 30;
               cn.Postpayment__c = 30;
               cn.Prepayment__c = 40;
               cn.ContractNumber__c = 'TT/11112022';
               insert cn;
               
               Specification__c sn = new Specification__c();
               sn.Prepayment_days__c = 5;
               sn.Partpayment_days__c = 5;
               sn.Postpayment_days__c = 5;              
               sn.Opportunity__c = opportunity.Id;
               sn.Quote__c = quote.Id;
               sn.SpecificationDate__c = Date.valueOf('2013-04-10'); 
               sn.CompanyDeliverTo__c = 'test';
               sn.DeliveryDuration__c = 'test';
               sn.Partpayment__c = 30;
               sn.Postpayment__c = 30;
               sn.Prepayment__c = 40;
               sn.Contract__c = cn.ID;
               insert sn;    
               
               ApexPages.StandardController sc = new ApexPages.StandardController(cn);
               ContractExtensionController cec = new ContractExtensionController(sc);
               System.assertEquals(cec.getContractDate(), '«10» апреля 2013 г.');
               System.assertEquals(cec.getContractSpecificationDate(), '«10» апреля 2013 г.');
               cec.getContractProducts();
               cec.getContractNDS();
               cec.getContractCount();
               cec.getContractTotal();
               cec.getContractTotalWithoutNDS();
               cec.getContractTotalStr();
               cec.getContractNDSStr();
               cec.getPaymentText();
               cec.getPaymentText2();
               cec.getBankDaysStr(Decimal.valueOf(5));
               cec.getBankDaysStr(Decimal.valueOf(12));               
               cec.getBankDaysStr(Decimal.valueOf(55));
               cec.getDelivery();
               cec.getAddressPost();
               cec.getCProduct();
               cec.getspecConditionPointNumber();
               cec.num2str(Decimal.valueOf('12'));
               cec.num2str(Decimal.valueOf('12222'));
               cec.num2str(Decimal.valueOf('12222222'));
               cec.num2str(Decimal.valueOf('12222222222'));               
                        
               
               pageRef = Page.SpecificationPDF;
               Test.setCurrentPageReference(pageRef);
               
               ApexPages.StandardController scs = new ApexPages.StandardController(sn);
               SpecificationExtensionController sec = new SpecificationExtensionController(scs);
               System.assertEquals(sec.getContractDate(), '«10» апреля 2013 г.');
               System.assertEquals(sec.getContractSpecificationDate(), '«10» апреля 2013 г.');
               sec.getContract();
               sec.getContractProducts();
               sec.getContractNDS();
               sec.getContractCount();
               sec.getContractTotal();
               sec.getContractTotalWithoutNDS();
               sec.getContractTotalStr();
               sec.getContractNDSStr();
               sec.getPaymentText();
               sec.getPaymentText2();
               sec.getBankDaysStr(Decimal.valueOf(5));
               sec.getBankDaysStr(Decimal.valueOf(12));               
               sec.getBankDaysStr(Decimal.valueOf(55));
               sec.getDelivery();
               sec.getAddressPost();
               sec.getCProduct();
               sec.getspecConditionPointNumber();
               sec.num2str(Decimal.valueOf('12'));
               sec.num2str(Decimal.valueOf('12222'));
               sec.num2str(Decimal.valueOf('12222222'));
               sec.num2str(Decimal.valueOf('12222222222'));
               
               pageRef = Page.ContractPDF;
               Test.setCurrentPageReference(pageRef);
               
               Pricebook2 pb22 = new Pricebook2(Name = 'test');
               insert pb22;
               Quote quote2 = new Quote(Name = 'test', OpportunityId = opportunity.Id, Organisation__c = account.id, Pricebook2Id = pb22.Id);
               insert quote2;                 
               Product2 p22 = new Product2(Name = 'test1 Мед');
               insert p22;
               PricebookEntry standardPrice2 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = p22.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
               insert standardPrice2;
               PricebookEntry pe2 = new PricebookEntry(UnitPrice = 100, IsActive = true, Product2Id = p22.Id, Pricebook2Id = pb22.Id);
               insert pe2;
               QuoteLineItem qln2 = new QuoteLineItem(quoteId = quote2.Id, PricebookEntryId = pe2.Id, Quantity = 1, UnitPrice = 100);
               insert qln2;    
               Opportunity opportunity2 = new Opportunity(Name='Test opp',StageName='test',CloseDate=Date.today(), Pricebook2Id = pb22.Id, UserTION__c = UT.id);
               insert opportunity2;
               OpportunityLineItem oln2 = new OpportunityLineItem(OpportunityId = Opportunity2.Id, PricebookEntryId = pe2.Id, Quantity = 1, UnitPrice = 100);
               insert oln2;
               OpportunityLineItem oln3 = new OpportunityLineItem(OpportunityId = Opportunity2.Id, PricebookEntryId = pe2.Id, Quantity = 1, UnitPrice = 200);
               insert oln3;
               Contract cn2 = new Contract();
               cn2.Prepayment_days__c = 5;
               cn2.Partpayment_days__c = 5;
               cn2.Postpayment_days__c = 5;              
               cn2.ProjectName__c = opportunity.Id;
               cn2.Smeta__c = quote2.Id;
               cn2.AccountId = account.Id;
               cn2.AccountCEO__c = 'test';
               cn2.AccountBillingName__c = 'test';
               cn2.AccountCEOAct__c = 'test';
               cn2.SignatureInitials__c = 'test';
               cn2.SpecificationDate__c = Date.valueOf('2013-04-10'); 
               cn2.SpecificationType__c = 'Экспорт';
               cn2.DeliveryCondition__c = 'За счет Покупателя. Покупатель оплачивает счет от транспортной компании';
               cn2.StartDate =  Date.valueOf('2013-04-10');
               cn2.CompanyDeliverTo__c = 'test';
               cn2.DeliveryDuration__c = 'test';
               cn2.Partpayment__c = 0;
               cn2.Postpayment__c = 0;
               cn2.Prepayment__c = 100;               
               cn2.ContractNumber__c = 'TT/11112022';
               insert cn2;
               
               Specification__c sn2 = new Specification__c();
               sn2.Prepayment_days__c = 5;
               sn2.Partpayment_days__c = 5;
               sn2.Postpayment_days__c = 5;              
               sn2.opportunity__c = opportunity.Id;
               sn2.quote__c = quote2.Id;
               sn2.SpecificationDate__c = Date.valueOf('2013-04-10'); 
               sn2.SpecificationType__c = 'Экспорт';
               sn2.DeliveryCondition__c = 'За счет Покупателя. Покупатель оплачивает счет от транспортной компании';
               sn2.CompanyDeliverTo__c = 'test';
               sn2.DeliveryDuration__c = 'test';
               sn2.Partpayment__c = 0;
               sn2.Postpayment__c = 0;
               sn2.Prepayment__c = 100;               
               sn2.Contract__c = cn2.ID;
               insert sn2;
               
               ApexPages.StandardController sc2 = new ApexPages.StandardController(cn2);
               ContractExtensionController cec2 = new ContractExtensionController(sc2);
               cec2.getContractProducts();
               cec2.getContractNDS();
               cec2.getContractCount();
               cec2.getContractTotal();
               cec2.getContractTotalWithoutNDS();
               cec2.getContractTotalStr();
               cec2.getContractNDSStr();
               cec2.getPaymentText();
               cec2.getPaymentText2();
               cec2.getBankDaysStr(Decimal.valueOf(5));
               cec2.getBankDaysStr(Decimal.valueOf(12));               
               cec2.getBankDaysStr(Decimal.valueOf(55));
               cec2.getDelivery();
               cec2.getAddressPost();
               cec2.getCProduct();
               cec2.getspecConditionPointNumber();
               cec2.num2str(Decimal.valueOf('12'));
               cec2.num2str(Decimal.valueOf('12222'));
               cec2.num2str(Decimal.valueOf('12222222'));
               cec2.num2str(Decimal.valueOf('12222222222'));
               
               pageRef = Page.SpecificationPDF;
               Test.setCurrentPageReference(pageRef);
               ApexPages.StandardController scs2 = new ApexPages.StandardController(sn2);
               SpecificationExtensionController sec2 = new SpecificationExtensionController(scs2);
               sec2.getContractProducts();
               sec2.getContractNDS();
               sec2.getContractCount();
               sec2.getContractTotal();
               sec2.getContractTotalWithoutNDS();
               sec2.getContractTotalStr();
               sec2.getContractNDSStr();
               sec2.getPaymentText();
               sec2.getPaymentText2();
               sec2.getBankDaysStr(Decimal.valueOf(5));
               sec2.getBankDaysStr(Decimal.valueOf(12));               
               sec2.getBankDaysStr(Decimal.valueOf(55));
               sec2.getDelivery();
               sec2.getAddressPost();
               sec2.getCProduct();
               sec2.getspecConditionPointNumber();
               sec2.num2str(Decimal.valueOf('12'));
               sec2.num2str(Decimal.valueOf('12222'));
               sec2.num2str(Decimal.valueOf('12222222'));
               sec2.num2str(Decimal.valueOf('12222222222'));
               
           }  
      }  
 }