unpackaged/main/default/objects/Account/fields/ShippingCountry__c.field-meta.xml
<CustomField>
    <fullName>ShippingCountry__c</fullName>
    <label>Страна (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Россия</fullName>
            </value>
            <value>
                <fullName>Беларусь</fullName>
            </value>
            <value>
                <fullName>Казахстан</fullName>
            </value>
            <value>
                <fullName>Украина</fullName>
            </value>
            <value>
                <fullName>Словакия</fullName>
            </value>
            <value>
                <fullName>Литва</fullName>
            </value>
            <value>
                <fullName>Монголия</fullName>
            </value>
            <value>
                <fullName>Австрия</fullName>
            </value>
            <value>
                <fullName>Приднестровская республика</fullName>
            </value>
            <value>
                <fullName>Узбекистан</fullName>
            </value>
            <value>
                <fullName>Молдавия</fullName>
            </value>
            <value>
                <fullName>Абхазия</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ShippingRegion__c.field-meta.xml
<CustomField>
    <fullName>ShippingRegion__c</fullName>
    <label>Область/Регион (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ShippingCountry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Республика Кабардино-Балкарская</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесская</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия — Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва (Тува)</fullName>
            </value>
            <value>
                <fullName>Республика Удмуртская</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Республика Чеченская</fullName>
            </value>
            <value>
                <fullName>Республика Чувашская</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Забайкальский край</fullName>
            </value>
            <value>
                <fullName>Камчатский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Пермский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
            <value>
                <fullName>Ставропольский край</fullName>
            </value>
            <value>
                <fullName>Хабаровский край</fullName>
            </value>
            <value>
                <fullName>Москва</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Организацию</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>mDVt</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/act__c/act__c.object-meta.xml
<CustomObject>
    <label>Акт шеф-монтажа</label>
    <nameField>
        <displayFormat>{000}/{MM}.{YY}</displayFormat>
        <label>Номер акта</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Акты шеф-монтажа</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/act__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Акты шеф-монтажа</relationshipLabel>
    <relationshipName>Act</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Проект (Сделка)</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Оборудование на объекте</relationshipLabel>
    <relationshipName>activeOpp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/ServiceFreq__c.field-meta.xml
<CustomField>
    <fullName>ServiceFreq__c</fullName>
    <label>Периодичность обслуживания (дни)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>180</fullName>
            </value>
            <value>
                <fullName>365</fullName>
                <default>true</default>
                <label>365</label>
            </value>
            <value>
                <fullName>1825</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Конкурс</label>
    <nameField>
        <displayFormat>Конкурс-{00000000}</displayFormat>
        <label>Номер конкурса</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Конкурсы</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Auction__c/fields/AuctionName__c.field-meta.xml
<CustomField>
    <fullName>AuctionName__c</fullName>
    <label>Наименование заказа</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Auction__c/fields/AuctionNumber__c.field-meta.xml
<CustomField>
    <fullName>AuctionNumber__c</fullName>
    <label>Номер заказа на сайте госзакупок</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Auction__c/fields/AuctionRegion__c.field-meta.xml
<CustomField>
    <fullName>AuctionRegion__c</fullName>
    <label>Регион</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Auction__c/fields/AuctionStatus__c.field-meta.xml
<CustomField>
    <fullName>AuctionStatus__c</fullName>
    <label>Статус</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Не просмотрен</fullName>
                <default>true</default>
                <label>Не просмотрен</label>
            </value>
            <value>
                <fullName>Не профиль</fullName>
            </value>
            <value>
                <fullName>Конвертирован в проект</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Auction__c/fields/AuctionURLLink__c.field-meta.xml
<CustomField>
    <fullName>AuctionURLLink__c</fullName>
    <label>Ссылка на сайт госзакупок</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/HiddenStageNameBeforeApprovalStarts__c.field-meta.xml
<CustomField>
    <fullName>HiddenStageNameBeforeApprovalStarts__c</fullName>
    <label>Этап до процесса утверждения</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/needSendNotification__c.field-meta.xml
<CustomField>
    <fullName>needSendNotification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>needSendNotification</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/StartWorkingProducts__c.field-meta.xml
<CustomField>
    <fullName>StartWorkingProducts__c</fullName>
    <label>Дата ввода оборудования в эксплуатацию</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroup__c/OpportunityGroup__c.object-meta.xml
<CustomObject>
    <label>Группа проекта</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Идентификатор</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Группа проекта</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OpportunityGroup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>OppGroup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroup__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <label>Роль</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Менеджер по продажам</fullName>
            </value>
            <value>
                <fullName>Региональный менеджер по продажам</fullName>
            </value>
            <value>
                <fullName>Руководитель отдела продаж</fullName>
            </value>
            <value>
                <fullName>Руководитель сервисной службы</fullName>
            </value>
            <value>
                <fullName>Сервисный инженер</fullName>
            </value>
            <value>
                <fullName>Проектировщик</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/ProjectMember__c.object-meta.xml
<CustomObject>
    <label>Контрагент</label>
    <nameField>
        <displayFormat>ProjectMember-{0}</displayFormat>
        <label>Код контрагента</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Контрагенты</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProjectMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Организация</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Проекты (участник)</relationshipLabel>
    <relationshipName>Project_membersWMZ8</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <label>Проект</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Контрагенты</relationshipLabel>
    <relationshipName>Project_memberHUKx</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/fields/ProjectRoles__c.field-meta.xml
<CustomField>
    <fullName>ProjectRoles__c</fullName>
    <label>Роли в проекте</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Генпроектировщик</fullName>
            </value>
            <value>
                <fullName>Субпроектировщик</fullName>
            </value>
            <value>
                <fullName>Генподрядчик</fullName>
            </value>
            <value>
                <fullName>Субподрядчик</fullName>
            </value>
            <value>
                <fullName>Эксплуатация</fullName>
            </value>
            <value>
                <fullName>Заказчик</fullName>
            </value>
            <value>
                <fullName>Дилер</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>Пользователь ТИОН</label>
    <nameField>
        <label>ФИО</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Пользователи ТИОН</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Профиль пользователя</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCustom</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestOpportunityExtension.cls
@isTest(seeAllData=true)
private class TestOpportunityExtension {  
    static testMethod void TestOpportunityExtentionController() {
        RecordType recType1 = [select developername from RecordType where Name='Объект на проектирование' and SobjectType = 'Opportunity'];   
        Auction__c auction = new Auction__c(AuctionName__c = 'Description',
                                            AuctionNumber__c = '123',
                                            AuctionRegion__c = 'Республика Татарстан',
                                            AuctionURLLink__c = 'http://salesforce.com',
                                            AuctionStatus__c = 'Не просмотрен');
        insert auction;
        
        Account account = new Account(Name='Test acc',
                                      Type='Монтажник',
                                      Phone='1234',
                                      ShippingCountry__c='Россия',
                                      ShippingRegion__c='Москва');
        insert account;
              
        PageReference pageRef = Page.CustomProjectPage;
        pageRef.getParameters().put('RecordType',recType1.Id);
        pageRef.getParameters().put('auctionId',auction.Id);
        Test.setCurrentPageReference(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(new Opportunity());
        OpportunityExtentionController controller = new OpportunityExtentionController(sc);
        controller.opp.Name='Test opp';
        controller.opp.StageName='Подбор оборудования';
        controller.opp.CloseDate=Date.today();
        controller.opp.ownerID=userinfo.getUserID();
        controller.sendNotification = true;
        controller.opp.needSendNotification__c = true;
        controller.save();
        
        Opportunity opp = [SELECT id FROM opportunity Where OwnerId = :userinfo.getUserID() limit 1];
        controller.opp.id = opp.id;
        controller.getDynamicForm();
        controller.opp.RecordTypeId = recType1.Id;     
        ProjectMember__c pmc = new ProjectMember__c(AccountId__c = [SELECT id FROM Account Limit 1].id, OpportunityId__c = opp.id, ProjectRoles__c = 'Генпроектировщик, Генподрядчик');
        insert pmc;
        controller.opp.StageName='Подбор оборудования';
        controller.getShowNextStage();
        controller.saveNextStage();
        
        
        asset asset = new asset(Name = '1',ServiceFreq__c = '3', Opportunity__c = opp.id, AccountId = [SELECT id FROM Account Limit 1].id);
        insert asset;
        
        controller.opp.HiddenStageNameBeforeApprovalStarts__c = 'test';
        controller.opp.StageName='Отслеживание конкурса на проектирование';
        controller.saveNextStage();
        controller.opp.StageName='Переговоры с проектировщиком';
        controller.saveNextStage();
        controller.opp.StageName='Подбор оборудования';
        controller.saveNextStage();
        controller.opp.StageName='КП Проектировщику';
        controller.saveNextStage();
        controller.opp.StageName='Отслеживание конкурса на монтаж';
        controller.saveNextStage();
        
        controller.opp.StageName='Шеф-монтаж';
        controller.saveNextStage();
        
        controller.opp.StageName='Гарантийная эксплуатация'; 
        
        opp.StageName='Гарантийная эксплуатация'; 
        opp.StartWorkingProducts__c = date.today();
        update opp;  
        controller.saveNextStage();
        controller.opp.StageName='Шеф-монтаж';
        opp.StageName='Шеф-монтаж';
        act__c act = new act__c(Opportunity__c = opp.id);
        insert act;
        
        opp.StartWorkingProducts__c = date.today();
        controller.opp.StartWorkingProducts__c = opp.StartWorkingProducts__c;
        controller.saveNextStage();
        controller.opp.StageName='Отгрузка оборудования';
        controller.saveNextStage();
        controller.opp.StageName='Холодный звонок';
        controller.saveNextStage();
        controller.opp.StageName='Переговоры (обсуждение условий)';
        controller.saveNextStage();
        
        User admUser = [SELECT Id, ProfileId FROM user Where LastName = 'Администрация']; 
        List<User__c> tionUser = [SELECT User__c, Id FROM User__c WHERE User__c = :admUser.Id];    
        if(!tionUser.isEmpty()){
            OpportunityGroup__c oppgroup = new OpportunityGroup__c();
            oppgroup.Opportunity__c = opp.ID;
            oppgroup.UserRole__c = 'Руководитель отдела продаж';                    
            oppgroup.UserTION__c = tionUser[0].ID;
            insert oppgroup;
            controller.opp.HiddenStageNameBeforeApprovalStarts__c = null;  
            controller.opp.StageName='Государственная экспертиза проекта';
            controller.opp.needStateReview__c = true;
            opp.HiddenStageNameBeforeApprovalStarts__c = null;
            opp.StageName='Государственная экспертиза проекта';
            opp.needStateReview__c = true;
            update opp; 
            controller.saveNextStage();     
        }
        
        
    }
    
    static testMethod void TestOpportunityExtentionController2() {
        RecordType recType1 = [select developername from RecordType where Name='Объект на проектирование' and SobjectType = 'Opportunity'];     
        RecordType recType2 = [select developername from RecordType where Name='Объект на монтаж' and SobjectType = 'Opportunity'];
        RecordType recType3 = [select developername from RecordType where Name='Продажа Тион О2 дилерам' and SobjectType = 'Opportunity'];
        Auction__c auction = new Auction__c(AuctionName__c = 'Description',
                                            AuctionNumber__c = '123',
                                            AuctionRegion__c = 'Республика Татарстан',
                                            AuctionURLLink__c = 'http://salesforce.com',
                                            AuctionStatus__c = 'Не просмотрен');
        insert auction;
        
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(new Opportunity());
        OpportunityExtentionController controller = new OpportunityExtentionController(sc);
        Opportunity opp = [SELECT id FROM opportunity Where OwnerId = :userinfo.getUserID() limit 1];
        
            PageReference pageRef = Page.CustomProjectPage;
            pageRef.getParameters().put('RecordType',recType2.Id);
            pageRef.getParameters().put('auctionId',auction.Id);
            Test.setCurrentPageReference(pageRef);
            sc = new ApexPages.StandardController(new Opportunity());
            controller = new OpportunityExtentionController(sc);
            controller.opp.Name='Test opp';
            controller.opp.StageName='Подбор оборудования';
            controller.opp.CloseDate=Date.today();
            controller.save();
        
        pageRef = Page.CustomProjectPage;
        pageRef.getParameters().put('RecordType',recType3.Id);
        pageRef.getParameters().put('auctionId',NULL);
        Test.setCurrentPageReference(pageRef);
        sc = new ApexPages.StandardController(new Opportunity());
        controller = new OpportunityExtentionController(sc);
        controller.opp.Name='Test opp';
        controller.opp.StageName='Подбор оборудования';
        controller.opp.CloseDate=Date.today();
        Profile profile = [select id, Name from profile where Name = 'Проектировщик'];    
        User user = new User(alias = 'tt04', email='testtest04@test.com', emailencodingkey='UTF-8', lastname='Проектировщик', languagelocalekey='en_US', localesidkey='en_US', profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='testtest04@test.com');  
        insert user;  
        System.RunAs(user){  
            controller.save();
        }
        
        User rop = [SELECT Id, ProfileId FROM user Where LastName = 'Администрация']; 
        List<User__c> UT = [SELECT User__c, Id FROM User__c WHERE User__c = :rop.Id];    
        if(!UT.isEmpty()){
            OpportunityGroup__c og1 = new OpportunityGroup__c();
            og1.Opportunity__c = opp.ID;
            og1.UserRole__c = 'Региональный менеджер по продажам';                    
            og1.UserTION__c = UT[0].ID;
            insert og1;        
            opp.approval__c = true;
            update opp;
        }        
        
        opp.StageName='Отгрузка оборудования';
        update opp;
    }    
}