unpackaged/main/default/objects/Account/fields/ShippingCountry__c.field-meta.xml
<CustomField>
    <fullName>ShippingCountry__c</fullName>
    <label>Страна (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Россия</fullName>
            </value>
            <value>
                <fullName>Беларусь</fullName>
            </value>
            <value>
                <fullName>Казахстан</fullName>
            </value>
            <value>
                <fullName>Украина</fullName>
            </value>
            <value>
                <fullName>Словакия</fullName>
            </value>
            <value>
                <fullName>Литва</fullName>
            </value>
            <value>
                <fullName>Монголия</fullName>
            </value>
            <value>
                <fullName>Австрия</fullName>
            </value>
            <value>
                <fullName>Приднестровская республика</fullName>
            </value>
            <value>
                <fullName>Узбекистан</fullName>
            </value>
            <value>
                <fullName>Молдавия</fullName>
            </value>
            <value>
                <fullName>Абхазия</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ShippingRegion__c.field-meta.xml
<CustomField>
    <fullName>ShippingRegion__c</fullName>
    <label>Область/Регион (фактическая)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ShippingCountry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Республика Кабардино-Балкарская</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесская</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия — Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва (Тува)</fullName>
            </value>
            <value>
                <fullName>Республика Удмуртская</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Республика Чеченская</fullName>
            </value>
            <value>
                <fullName>Республика Чувашская</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Забайкальский край</fullName>
            </value>
            <value>
                <fullName>Камчатский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Пермский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
            <value>
                <fullName>Ставропольский край</fullName>
            </value>
            <value>
                <fullName>Хабаровский край</fullName>
            </value>
            <value>
                <fullName>Москва</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Организацию</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>mDVt</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/needSendNotification__c.field-meta.xml
<CustomField>
    <fullName>needSendNotification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>needSendNotification</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник ответственный за Проект</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Возможности</relationshipLabel>
    <relationshipName>mExE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/ProductionOrder__c.object-meta.xml
<CustomObject>
    <label>Производственный заказ</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Имя заказа</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Производственные заказы</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProductionOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Контрагент</label>
    <referenceTo>ProjectMember__c</referenceTo>
    <relationshipLabel>Производственные заказы</relationshipLabel>
    <relationshipName>POsQT4</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/AccountContacts__c.field-meta.xml
<CustomField>
    <fullName>AccountContacts__c</fullName>
    <label>Контакты контрагента (ФИО, адрес, тел.)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Адрес объекта</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/DeliveryPay__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPay__c</fullName>
    <label>Оплата доставки</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Нет</fullName>
                <default>true</default>
                <label>Нет</label>
            </value>
            <value>
                <fullName>За счет Покупателя. Покупатель оплачивает счет от транспортной компании</fullName>
            </value>
            <value>
                <fullName>Самовывоз в течение 5 дней после уведомления</fullName>
            </value>
            <value>
                <fullName>Поставщик доставляет своими силами. Стоимость доставки входит в стоимость оборудования</fullName>
            </value>
            <value>
                <fullName>За счет Покупателя. Покупатель оплачивает счет от Тион</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Объект, название</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Производственные заказы</relationshipLabel>
    <relationshipName>ProductionOrderQOPh</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ответственный за производственный заказ</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PORlQN</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/SubmissionDate__c.field-meta.xml
<CustomField>
    <fullName>SubmissionDate__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <label>Дата представления утвержденной заявки</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник, ответственный за заказ</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Производственные заказы</relationshipLabel>
    <relationshipName>POh4RA</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/ProjectMember__c.object-meta.xml
<CustomObject>
    <label>Контрагент</label>
    <nameField>
        <displayFormat>ProjectMember-{0}</displayFormat>
        <label>Код контрагента</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Контрагенты</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProjectMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Организация</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Проекты (участник)</relationshipLabel>
    <relationshipName>Project_membersWMZ8</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <label>Проект</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Контрагенты</relationshipLabel>
    <relationshipName>Project_memberHUKx</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/ProjectMember__c/fields/ProjectRoles__c.field-meta.xml
<CustomField>
    <fullName>ProjectRoles__c</fullName>
    <label>Роли в проекте</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Генпроектировщик</fullName>
            </value>
            <value>
                <fullName>Субпроектировщик</fullName>
            </value>
            <value>
                <fullName>Генподрядчик</fullName>
            </value>
            <value>
                <fullName>Субподрядчик</fullName>
            </value>
            <value>
                <fullName>Эксплуатация</fullName>
            </value>
            <value>
                <fullName>Заказчик</fullName>
            </value>
            <value>
                <fullName>Дилер</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Организация</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Сметы</relationshipLabel>
    <relationshipName>OrganisationQuotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Смету</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Сметы</relationshipLabel>
    <relationshipName>mDWD</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>Пользователь ТИОН</label>
    <nameField>
        <label>ФИО</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Пользователи ТИОН</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Профиль пользователя</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCustom</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestProductionOrder.cls
@isTest(seeAllData=true)
private class TestProductionOrder {  
      static testMethod void Test1() {  
           Profile profile = [select id, Name from profile where Name = 'Менеджер по продажам'];    
           Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
           User user = new User(alias = 'tt05', email='testtest05@test.com', emailencodingkey='UTF-8', lastname='Менеджер по продажам', languagelocalekey='en_US', localesidkey='en_US', profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='testtest05@test.com');  
           insert user;  
           System.RunAs(user){                 
               PageReference pageRef = Page.ProductionOrder;
               Test.setCurrentPageReference(pageRef);
               Account account = new Account(Name='Test acc',
                                        Type='Монтажник',
                                        Phone='1234',
                                        ShippingCountry__c='Россия',
                                        ShippingRegion__c='Москва');
               insert account;               
               Pricebook2 pb2 = new Pricebook2(Name = 'test');
               insert pb2;
                User__c UT = new User__c(User__c = UserInfo.getUserId(), Name = 'Менеджер по продажам');
                insert UT;
               Opportunity opportunity = new Opportunity(Name='Test opp',StageName='test',CloseDate=Date.today(), Pricebook2Id = pb2.Id, UserTION__c = UT.id, needSendNotification__c = true);
               insert opportunity;               
               ProjectMember__c PMC = new ProjectMember__c(ProjectRoles__c = 'Генпроектировщик', OpportunityId__c = opportunity.id, AccountId__c = account.id);
               insert PMC;               
               Quote quote = new Quote(Name = 'test', OpportunityId = opportunity.Id, Organisation__c = account.id, Pricebook2Id = pb2.Id);
               insert quote;                 
               Product2 p2 = new Product2(Name = 'test1 Пром');
               insert p2;
               PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = p2.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
               insert standardPrice;
               PricebookEntry pe = new PricebookEntry(UnitPrice = 100, IsActive = true, Product2Id = p2.Id, Pricebook2Id = pb2.Id);
               insert pe;
               QuoteLineItem qln = new QuoteLineItem(quoteId = quote.Id, PricebookEntryId = pe.Id, Quantity = 1, UnitPrice = 100);
               insert qln;
               OpportunityLineItem oln = new OpportunityLineItem(OpportunityId = Opportunity.Id, PricebookEntryId = pe.Id, Quantity = 1, UnitPrice = 100);
               insert oln;   
               
               ApexPages.StandardController sc = new ApexPages.StandardController(new ProductionOrder__c());
               ProductionOrderExtentionController controller = new ProductionOrderExtentionController(sc);               
               controller.PO.owner__c=userinfo.getUserID();
               controller.PO.opportunity__c = opportunity.ID;
               controller.setQuote(quote.ID);
               controller.PO.UserTION__c = UT.ID;
               controller.PO.SubmissionDate__c = Date.today();
               controller.PO.Account__c = PMC.Id;
               controller.PO.AccountContacts__c = 'test';
               controller.PO.Address__c = 'test';
               controller.PO.DeliveryPay__c = 'Самовывоз в течение 5 дней после уведомления';
               controller.save();   
               
               controller.getDynamicForm();
               insert controller.PO;
           }  
      }  
 }