unpackaged/main/default/objects/Account/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Организацию</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Организации</relationshipLabel>
    <relationshipName>mDVt</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/ProductionOrder__c.object-meta.xml
<CustomObject>
    <label>Производственный заказ</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Имя заказа</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Производственные заказы</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProductionOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Контрагент</label>
    <referenceTo>ProjectMember__c</referenceTo>
    <relationshipLabel>Производственные заказы</relationshipLabel>
    <relationshipName>POsQT4</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/AccountContacts__c.field-meta.xml
<CustomField>
    <fullName>AccountContacts__c</fullName>
    <label>Контакты контрагента (ФИО, адрес, тел.)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Адрес объекта</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/DeliveryPay__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPay__c</fullName>
    <label>Оплата доставки</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Нет</fullName>
                <default>true</default>
                <label>Нет</label>
            </value>
            <value>
                <fullName>За счет Покупателя. Покупатель оплачивает счет от транспортной компании</fullName>
            </value>
            <value>
                <fullName>Самовывоз в течение 5 дней после уведомления</fullName>
            </value>
            <value>
                <fullName>Поставщик доставляет своими силами. Стоимость доставки входит в стоимость оборудования</fullName>
            </value>
            <value>
                <fullName>За счет Покупателя. Покупатель оплачивает счет от Тион</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/EquipmentDate__c.field-meta.xml
<CustomField>
    <fullName>EquipmentDate__c</fullName>
    <label>Дата производства оборудования</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Объект, название</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Производственные заказы</relationshipLabel>
    <relationshipName>ProductionOrderQOPh</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ответственный за производственный заказ</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PORlQN</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Производственный заказ на основе Сметы</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Производственные заказы</relationshipLabel>
    <relationshipName>PO0cEs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/ShipmentDate__c.field-meta.xml
<CustomField>
    <fullName>ShipmentDate__c</fullName>
    <label>Дата отгрузки оборудования на объект</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/SubmissionDate__c.field-meta.xml
<CustomField>
    <fullName>SubmissionDate__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <label>Дата представления утвержденной заявки</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/UID_1C__c.field-meta.xml
<CustomField>
    <fullName>UID_1C__c</fullName>
    <label>Номер заказа поставщику в 1С</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrder__c/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник, ответственный за заказ</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Производственные заказы</relationshipLabel>
    <relationshipName>POh4RA</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/ProductionOrderItemLine__c.object-meta.xml
<CustomObject>
    <label>Продукт заказа</label>
    <nameField>
        <displayFormat>POLI-{0000000}</displayFormat>
        <label>Номер продукта заказа</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Продукты заказа</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/CountItems__c.field-meta.xml
<CustomField>
    <fullName>CountItems__c</fullName>
    <label>Количество</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/CustomBodyColor__c.field-meta.xml
<CustomField>
    <fullName>CustomBodyColor__c</fullName>
    <label>Нестандартный цвет корпуса (RAL)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/CustomConnection__c.field-meta.xml
<CustomField>
    <fullName>CustomConnection__c</fullName>
    <description>Нестандартные присоединительные размеры (Впр х Шпр),мм</description>
    <inlineHelpText>Нестандартные присоединительные размеры (Впр х Шпр),мм</inlineHelpText>
    <label>Нестандартные п. размеры  (Впр х Шпр),мм</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/CustomMounting__c.field-meta.xml
<CustomField>
    <fullName>CustomMounting__c</fullName>
    <label>Нестандартный способ крепления и монтажа</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/CustomPerformance__c.field-meta.xml
<CustomField>
    <fullName>CustomPerformance__c</fullName>
    <label>Нестандартная производительность, м3/ча</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/CustomPressure__c.field-meta.xml
<CustomField>
    <fullName>CustomPressure__c</fullName>
    <label>Нестандартный перепад давления, Па</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/CustomSize__c.field-meta.xml
<CustomField>
    <fullName>CustomSize__c</fullName>
    <label>Нестандартные габариты (ДхШхВ), мм</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/LimitSizeShipping__c.field-meta.xml
<CustomField>
    <fullName>LimitSizeShipping__c</fullName>
    <label>Ограничение на транспорт. габариты</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/medprom__c.field-meta.xml
<CustomField>
    <fullName>medprom__c</fullName>
    <label>Мед/Пром</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Нет</fullName>
                <default>true</default>
                <label>Нет</label>
            </value>
            <value>
                <fullName>Мед</fullName>
            </value>
            <value>
                <fullName>Пром</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/NumberPP__c.field-meta.xml
<CustomField>
    <fullName>NumberPP__c</fullName>
    <label>№ пп</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/ProductionOrder__c.field-meta.xml
<CustomField>
    <fullName>ProductionOrder__c</fullName>
    <label>Производственный заказ</label>
    <referenceTo>ProductionOrder__c</referenceTo>
    <relationshipLabel>Продукты заказа</relationshipLabel>
    <relationshipName>POLIxaK2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Продукт</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/SectionComposition__c.field-meta.xml
<CustomField>
    <fullName>SectionComposition__c</fullName>
    <label>Компоновка секций</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/SeparateControl__c.field-meta.xml
<CustomField>
    <fullName>SeparateControl__c</fullName>
    <label>Наличие выносного пульта</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Нет</fullName>
                <default>true</default>
                <label>Нет</label>
            </value>
            <value>
                <fullName>Да</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/SideService__c.field-meta.xml
<CustomField>
    <fullName>SideService__c</fullName>
    <label>Сторона обслуживания</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>-R</fullName>
                <default>true</default>
                <label>-R</label>
            </value>
            <value>
                <fullName>-L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ProductionOrderItemLine__c/fields/SpecialNotes__c.field-meta.xml
<CustomField>
    <fullName>SpecialNotes__c</fullName>
    <label>Особые отметки</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник ответственный за Смету</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Сметы</relationshipLabel>
    <relationshipName>mDWD</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ProductionOrderExtentionController.cls
public class ProductionOrderExtentionController{
    public ProductionOrder__c PO;
    ID Quote;
    private final ApexPages.StandardController stdController;
    Map <Integer,String> monthNames = new Map<Integer,String> {1 => 'января',2 => 'февраля',3 => 'марта',
        4 => 'апреля', 5 => 'мая', 6 => 'июня', 7 => 'июля', 8 => 'августа', 9 => 'сентября', 10 => 'октября',
        11 => 'ноября', 12 => 'декабря'};

    public ProductionOrderExtentionController(ApexPages.StandardController controller) {
        stdController = controller;
        PO = (ProductionOrder__c)controller.getRecord();
    }
    
    public PageReference save() {    
        if (PO.id == NULL) PO.Quote__c = Quote;
        PageReference redirectPage;
        try { 
            redirectPage = stdController.save();               
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        return redirectPage;
    }
    
    public List<SelectOption> getQuoteItems() {
        List<SelectOption> options = new List<SelectOption>();
        List<Quote> qList = [SELECT ID, Name FROM Quote WHERE OpportunityId = :PO.Opportunity__c];
        for(Quote q:qList){
            options.add(new SelectOption(q.ID,q.Name));    
        }
        return options;
    }
    
    public ID getQuote() {
        return Quote;
    }
    
    public void setQuote(ID Quote) {
        this.Quote = Quote;
    }
    
    public Component.Apex.PageBlock getDynamicForm() {
        Component.Apex.PageBlock dynPageBlock = new Component.Apex.PageBlock();
        dynPageBlock.id = 'PageBlock';
        dynPageBlock.mode = 'edit';
        dynPageBlock.title = 'Редактировать производственный заказ';
        Component.Apex.PageBlockButtons dynPageBlockButtons = new Component.Apex.PageBlockButtons();
        Component.Apex.commandButton dynButtonSave = new Component.Apex.commandButton();
        dynButtonSave.expressions.action = '{!save}';
        dynButtonSave.value = 'Сохранить';
        Component.Apex.commandButton dynButtonCancel = new Component.Apex.commandButton();
        dynButtonCancel.expressions.action = '{!cancel}';
        dynButtonCancel.value = 'Отмена';
        dynButtonCancel.immediate = true;
        Component.Apex.PageMessages dynPageMessages = new Component.Apex.PageMessages();        
        Component.Apex.PageBlockSection dynPageBlockSection1 = new Component.Apex.PageBlockSection();
        dynPageBlockSection1.columns = 2;
        dynPageBlockSection1.collapsible = false;        
        Component.Apex.InputField fieldOpp = new Component.Apex.InputField();
        fieldOpp.id = 'Opp';
        fieldOpp.label = 'Проект';
        fieldOpp.expressions.value = '{!ProductionOrder__c.Opportunity__c}';
        Component.Apex.SelectOptions fieldQuoteOption = new Component.Apex.SelectOptions();
        fieldQuoteOption.id = 'QOP';
        fieldQuoteOption.expressions.value = '{!QuoteItems}';            
        Component.Apex.actionSupport actionOpp = new Component.Apex.actionSupport();
        actionOpp.event = 'onchange';        
        fieldOpp.childComponents.add(actionOpp);
        
        if (PO.id == NULL){
            Component.Apex.SelectList fieldQuote = new Component.Apex.SelectList();
            fieldQuote.id = 'Quote';
            try{fieldQuote.label = 'Смета';}catch(System.VisualforceException e){}
            fieldQuote.size = 1;
            fieldQuote.expressions.value = '{!Quote}';
            fieldQuote.childComponents.add(fieldQuoteOption);  
            dynPageBlockSection1.childComponents.add(fieldQuote);    
            dynPageBlockSection1.childComponents.add(fieldOpp);   
        }
        
        
        Component.Apex.InputField fieldOwner = new Component.Apex.InputField();
        fieldOwner.id = 'Owner';
        fieldOwner.required = true;
        fieldOwner.label = 'Ответственный за производственный заказ';
        fieldOwner.expressions.value = '{!ProductionOrder__c.Owner__c}';
        
        
        Component.Apex.InputField fieldUserTION = new Component.Apex.InputField();
        fieldUserTION.id = 'UserTION';
        fieldUserTION.required = true;
        fieldUserTION.label = 'Сотрудник, ответственный за производственный заказ';
        fieldUserTION.expressions.value = '{!ProductionOrder__c.UserTION__c}';
        
        
        Component.Apex.InputField fieldSubmissionDate = new Component.Apex.InputField();
        fieldSubmissionDate.id = 'SubmissionDate';
        fieldSubmissionDate.required = true;
        fieldSubmissionDate.label = 'Дата представления утвержденной заявки';
        fieldSubmissionDate.expressions.value = '{!ProductionOrder__c.SubmissionDate__c}';
        
        
        Component.Apex.InputField fieldUID_1C = new Component.Apex.InputField();
        fieldUID_1C.id = 'UID_1C';
        fieldUID_1C.label = 'Номер заказа поставщику в 1С';
        fieldUID_1C.expressions.value = '{!ProductionOrder__c.UID_1C__c}';
        
        
        Component.Apex.InputField fieldAccount = new Component.Apex.InputField();
        fieldAccount.id = 'Account';
        fieldAccount.required = true;
        fieldAccount.label = 'Контрагент';
        fieldAccount.expressions.value = '{!ProductionOrder__c.Account__c}';
        
        
        Component.Apex.InputField fieldAccountContacts = new Component.Apex.InputField();
        fieldAccountContacts.id = 'AccountContacts';
        fieldAccountContacts.required = true;
        fieldAccountContacts.label = 'Контакты контрагента (ФИО, адрес, тел.)';
        fieldAccountContacts.expressions.value = '{!ProductionOrder__c.AccountContacts__c}';
        
        
        Component.Apex.InputField fieldAddress = new Component.Apex.InputField();
        fieldAddress.id = 'Address';
        fieldAddress.required = true;
        fieldAddress.label = 'Адрес объекта';
        fieldAddress.expressions.value = '{!ProductionOrder__c.Address__c}';
        
        
        Component.Apex.InputField fieldDeliveryPay = new Component.Apex.InputField();
        fieldDeliveryPay.id = 'DeliveryPay';
        fieldDeliveryPay.required = true;
        fieldDeliveryPay.label = 'Оплата доставки';
        fieldDeliveryPay.expressions.value = '{!ProductionOrder__c.DeliveryPay__c}';
        
        
        Component.Apex.InputField fieldEquipmentDate = new Component.Apex.InputField();
        fieldEquipmentDate.id = 'EquipmentDate';
        fieldEquipmentDate.label = 'Дата производства оборудования';
        fieldEquipmentDate.expressions.value = '{!ProductionOrder__c.EquipmentDate__c}';
        
        
        Component.Apex.InputField fieldShipmentDate = new Component.Apex.InputField();
        fieldShipmentDate.id = 'ShipmentDate';
        fieldShipmentDate.label = 'Дата отгрузки оборудования на объект';
        fieldShipmentDate.expressions.value = '{!ProductionOrder__c.ShipmentDate__c}';
        
          
        dynPageBlockSection1.childComponents.add(fieldOwner);   
        dynPageBlockSection1.childComponents.add(fieldAccount);   
        dynPageBlockSection1.childComponents.add(fieldUserTION);   
        dynPageBlockSection1.childComponents.add(fieldAccountContacts);   
        dynPageBlockSection1.childComponents.add(fieldSubmissionDate);   
        dynPageBlockSection1.childComponents.add(fieldAddress);   
        dynPageBlockSection1.childComponents.add(fieldUID_1C);   
        dynPageBlockSection1.childComponents.add(fieldDeliveryPay);   
        dynPageBlockSection1.childComponents.add(fieldEquipmentDate);   
        dynPageBlockSection1.childComponents.add(fieldShipmentDate); 
        
        
        
        List<Quote> qList = [SELECT ID, Name FROM Quote WHERE OpportunityId = :PO.Opportunity__c];
        if(!qList.isEmpty()) dynPageBlockButtons.childComponents.add(dynButtonSave);   
        dynPageBlockButtons.childComponents.add(dynButtonCancel);
        dynPageBlock.childComponents.add(dynPageBlockButtons);
        dynPageBlock.childComponents.add(dynPageMessages);    
        dynPageBlock.childComponents.add(dynPageBlockSection1);
        return dynPageBlock;
    }
    
    public List<ProductionOrderItemLine__c> getProducts() {
        return [SELECT NumberPP__c, SideService__c, ProductionOrder__c, ProductName__c, SpecialNotes__c, LimitSizeShipping__c, CustomBodyColor__c, CustomMounting__c, 
                        CustomPressure__c, CustomConnection__c, CustomSize__c, CustomPerformance__c, SeparateControl__c, medprom__c, SectionComposition__c, CountItems__c
                FROM ProductionOrderItemLine__c WHERE ProductionOrder__c = :PO.Id];   
    }
    
    public string getSubmissionDate() {
        if(PO.SubmissionDate__c == NULL) return NULL;
        String day = PO.SubmissionDate__c.day().format();
        if(day.length()==1) {
            day = '0'+day;
        }
        String sDate = '«'+ day +'» '+monthNames.get(PO.SubmissionDate__c.month())+' '+PO.SubmissionDate__c.year()+' г.';
        return sDate;
    }
    
    public string getEquipmentDate() {
        if(PO.EquipmentDate__c == NULL) return NULL;
        String day = PO.EquipmentDate__c.day().format();
        if(day.length()==1) {
            day = '0'+day;
        }
        String sDate = '«'+ day +'» '+monthNames.get(PO.EquipmentDate__c.month())+' '+PO.EquipmentDate__c.year()+' г.';
        return sDate;
    }
    
    public string getShipmentDate() {
        if(PO.ShipmentDate__c == NULL) return NULL;
        String day = PO.ShipmentDate__c.day().format();
        if(day.length()==1) {
            day = '0'+day;
        }
        String sDate = '«'+ day +'» '+monthNames.get(PO.ShipmentDate__c.month())+' '+PO.ShipmentDate__c.year()+' г.';
        return sDate;
    }
    
    
}