unpackaged/main/default/objects/act__c/act__c.object-meta.xml
<CustomObject>
    <label>Акт шеф-монтажа</label>
    <nameField>
        <displayFormat>{000}/{MM}.{YY}</displayFormat>
        <label>Номер акта</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Акты шеф-монтажа</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/act__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Адрес</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/act__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Заказчик</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/act__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Дата</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/act__c/fields/Fio__c.field-meta.xml
<CustomField>
    <fullName>Fio__c</fullName>
    <label>Фамилия и инициалы (исполнитель)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/act__c/fields/FioClient__c.field-meta.xml
<CustomField>
    <fullName>FioClient__c</fullName>
    <label>Фамилия и инициалы (заказчик)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/act__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Акты шеф-монтажа</relationshipLabel>
    <relationshipName>Act</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/act__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Должность (исполнитель)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/act__c/fields/PositionClient__c.field-meta.xml
<CustomField>
    <fullName>PositionClient__c</fullName>
    <label>Должность (заказчик)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/buildingNumber__c.field-meta.xml
<CustomField>
    <fullName>buildingNumber__c</fullName>
    <label>Номер корпуса</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/level__c.field-meta.xml
<CustomField>
    <fullName>level__c</fullName>
    <label>Этаж</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Проект (Сделка)</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Оборудование на объекте</relationshipLabel>
    <relationshipName>activeOpp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/roomNumber__c.field-meta.xml
<CustomField>
    <fullName>roomNumber__c</fullName>
    <label>Номер комнаты</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/StartWorkingProducts__c.field-meta.xml
<CustomField>
    <fullName>StartWorkingProducts__c</fullName>
    <label>Дата ввода оборудования в эксплуатацию</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ActExtensionController.cls
public class ActExtensionController{
    private final act__c act;    
    private final act__c act_full;   
    private final ApexPages.StandardController stdController;
    
    Map <Integer,String> monthNames = new Map<Integer,String> {1 => 'января',2 => 'февраля',3 => 'марта',
        4 => 'апреля', 5 => 'мая', 6 => 'июня', 7 => 'июля', 8 => 'августа', 9 => 'сентября', 10 => 'октября',
        11 => 'ноября', 12 => 'декабря'};
            
    public ActExtensionController (ApexPages.StandardController controller) {
        stdController = controller;
        act = (act__c) controller.getRecord();
        
        if(act.id != NULL) act_full = [select Name, Address__c, Opportunity__c, Date__c, PositionClient__c, Position__c, Client__c, FioClient__c, 	Fio__c
                         from act__c where 
                         Id=:act.Id];
    }
    
    public String getStartDate(){
       Opportunity opp = [SELECT StartWorkingProducts__c FROM Opportunity WHERE Id = :act_full.Opportunity__c];
        
       String cDate = '«'+opp.StartWorkingProducts__c.day()+'» '+monthNames.get(opp.StartWorkingProducts__c.month())+' '+opp.StartWorkingProducts__c.year()+' г.';
       return cDate;
    }
    
    public String getStartDateMin(){
       Opportunity opp = [SELECT StartWorkingProducts__c FROM Opportunity WHERE Id = :act_full.Opportunity__c];
        
        String day = String.valueOf(opp.StartWorkingProducts__c.day());
        String month = String.valueOf(opp.StartWorkingProducts__c.month());
        if(opp.StartWorkingProducts__c.day() < 10) day = '0' + day;
        if(opp.StartWorkingProducts__c.month() < 10) month = '0' + month;
       String cDate = day+'.'+month+'.'+opp.StartWorkingProducts__c.year();
       return cDate;
    }
    
    public Integer getCountAssets(){
       return getAssetList().size();
    }    
    
    public List<Asset> getAssetList(){
        List<Asset> asset = [SELECT SerialNumber, Name, buildingNumber__c, level__c, roomNumber__c FROM Asset WHERE Opportunity__c = :act_full.Opportunity__c];
     	return asset;   
    }
}