unpackaged/main/default/objects/Opportunity/fields/ActualAmount__c.field-meta.xml
<CustomField>
    <fullName>ActualAmount__c</fullName>
    <label>Сумма прихода денег</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AuctionDateDesign__c.field-meta.xml
<CustomField>
    <fullName>AuctionDateDesign__c</fullName>
    <label>Дата конкурса на проектирование</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AuctionDateMounting__c.field-meta.xml
<CustomField>
    <fullName>AuctionDateMounting__c</fullName>
    <label>Дата конкурса на монтаж</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AuctionLinkDesign__c.field-meta.xml
<CustomField>
    <fullName>AuctionLinkDesign__c</fullName>
    <label>Конкурс на проектирование (госзакупки)</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AuctionLinkMounting__c.field-meta.xml
<CustomField>
    <fullName>AuctionLinkMounting__c</fullName>
    <label>Конкурс на монтаж (госзакупки)</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AuctionNameDesign__c.field-meta.xml
<CustomField>
    <fullName>AuctionNameDesign__c</fullName>
    <label>Наименование конкурса на проектирование</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AuctionNameMounting__c.field-meta.xml
<CustomField>
    <fullName>AuctionNameMounting__c</fullName>
    <label>Наименование конкурса на монтаж</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/DesignAuctionNumber__c.field-meta.xml
<CustomField>
    <fullName>DesignAuctionNumber__c</fullName>
    <label>Номер конкурса на проектирование</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/IsBillPaid__c.field-meta.xml
<CustomField>
    <fullName>IsBillPaid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Счет оплачен</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/isProblematicProject__c.field-meta.xml
<CustomField>
    <fullName>isProblematicProject__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Проблемный проект</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LastStageUpdated__c.field-meta.xml
<CustomField>
    <fullName>LastStageUpdated__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Временная метка последнего обновления этапа, изменяется автоматически триггером.</description>
    <label>Последнее обновление этапа</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/MountingAuctionNumber__c.field-meta.xml
<CustomField>
    <fullName>MountingAuctionNumber__c</fullName>
    <label>Номер конкурса на монтаж</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/needProlongation__c.field-meta.xml
<CustomField>
    <fullName>needProlongation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Вспомогательное поле для переходя в процесс утверждения при продлении</description>
    <label>needProlongation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/needProlongationText__c.field-meta.xml
<CustomField>
    <fullName>needProlongationText__c</fullName>
    <label>Причина продления</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ProjectProperties__c.field-meta.xml
<CustomField>
    <fullName>ProjectProperties__c</fullName>
    <label>Характеристики проекта</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Статус не ясен</fullName>
                <default>true</default>
                <label>Статус не ясен</label>
            </value>
            <value>
                <fullName>Есть категорийные помещения. Смета маленькая</fullName>
            </value>
            <value>
                <fullName>Есть категорийные помещения. Смета нормальная</fullName>
            </value>
            <value>
                <fullName>Есть категорийные помещения. Стоит Тион</fullName>
            </value>
            <value>
                <fullName>Есть категорийные помещения. Уточнить смету</fullName>
            </value>
            <value>
                <fullName>Нет категорийных помещений</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ProjectRegion__c.field-meta.xml
<CustomField>
    <fullName>ProjectRegion__c</fullName>
    <label>Регион проекта</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Москва</fullName>
            </value>
            <value>
                <fullName>Санкт-Петербург</fullName>
            </value>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Республика Кабардино-Балкарская</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесская</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия — Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва (Тува)</fullName>
            </value>
            <value>
                <fullName>Республика Удмуртская</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Республика Чеченская</fullName>
            </value>
            <value>
                <fullName>Республика Чувашская</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Забайкальский край</fullName>
            </value>
            <value>
                <fullName>Камчатский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Пермский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OpportunityProlongationController.cls
public class OpportunityProlongationController{
    public Opportunity opp;
    private final ApexPages.StandardController stdController;

    public OpportunityProlongationController(ApexPages.StandardController controller) {
        //controller.addFields(new String[]{'Name', 'StageName', 'LeadSource', 'ProjectProperties__c', 'isBillPaid__c', 'Description', 'Type', 'ProjectRegion__c', 'isProblematicProject__c', 'AuctionLinkDesign__c', 'AuctionLinkMounting__c', 'DesignAuctionNumber__c', 'MountingAuctionNumber__c', 'AuctionNameDesign__c', 'AuctionNameMounting__c', 'AuctionDateDesign__c', 'AuctionDateMounting__c', 'ActualAmount__c', 'CloseDate', 'RecordTypeId'});
        stdController = controller;
        opp = (Opportunity)controller.getRecord();
    }   
    
    public Component.Apex.PageBlock getShowLong() {
        Component.Apex.PageBlock dynPageBlock = new Component.Apex.PageBlock();
        dynPageBlock.id = 'PageBlock';
        dynPageBlock.mode = 'LongBut';
        dynPageBlock.title = 'Перейти к следующему этапу';
        Component.Apex.PageBlockButtons dynPageBlockButtons = new Component.Apex.PageBlockButtons();
        Component.Apex.commandButton dynButtonSave = new Component.Apex.commandButton();
        dynButtonSave.expressions.action = '{!saveLong}';
        dynButtonSave.value = 'Сохранить';
        Component.Apex.commandButton dynButtonCancel = new Component.Apex.commandButton();
        dynButtonCancel.expressions.action = '{!cancel}';
        dynButtonCancel.value = 'Отмена';
        dynButtonCancel.immediate = true;
        Component.Apex.PageBlockSection dynPageBlockSection = new Component.Apex.PageBlockSection();  
        Component.Apex.InputField dynText = new Component.Apex.InputField();
        dynText.id = 'needProlongationText__c';
        dynText.label = 'Укажите причину продления';
        dynText.expressions.value = '{!Opportunity.needProlongationText__c}';
        Component.Apex.PageMessages dynPageMessages = new Component.Apex.PageMessages();
        Component.Apex.PageMessage dynPageMessage = new Component.Apex.PageMessage();
        dynPageMessage.severity = 'warning';
        Boolean may = false;
        Profile profile = [Select Name from Profile where Id = :UserInfo.getProfileId()];
        User rop = [SELECT Id, ProfileId FROM user Where LastName = 'Менеджер по продажам'];        
        dynPageMessage.summary = 'Проект не нуждается в продлении.';
        if(opp.LastStageUpdated__c == NULL){
        	OpportunityHistory oh = [SELECT id, CreatedDate, StageName FROM OpportunityHistory WHERE OpportunityId = :opp.id AND isDeleted = false ORDER BY CreatedDate DESC LIMIT 1];
            opp.LastStageUpdated__c = oh.CreatedDate;
        }        
        if(
            (opp.StageName == 'Отслеживание конкурса на проектирование' && opp.LastStageUpdated__c.addDays(60) < datetime.now()) ||
            (opp.StageName == 'Переговоры с проектировщиком' && opp.LastStageUpdated__c.addDays(120) < datetime.now()) ||
            (opp.StageName == 'Подбор оборудования' && opp.LastStageUpdated__c.addDays(120) < datetime.now()) ||
            (opp.StageName == 'КП Проектировщику' && opp.LastStageUpdated__c.addDays(120) < datetime.now()) ||
            (opp.StageName == 'Получение копии проекта с оборудованием' && opp.LastStageUpdated__c.addDays(120) < datetime.now()) ||
            (opp.StageName == 'Государственная экспертиза проекта' && opp.LastStageUpdated__c.addDays(120) < datetime.now()) ||
            (opp.StageName == 'Отслеживание конкурса на монтаж' && opp.LastStageUpdated__c.addDays(365) < datetime.now()) ||
            (opp.StageName == 'Переговоры с генподрядчиком' && opp.LastStageUpdated__c.addDays(60) < datetime.now()) ||
            (opp.StageName == 'КП генподрядчику' && opp.LastStageUpdated__c.addDays(60) < datetime.now()) ||
            (opp.StageName == 'Заключение договора с генподрядчиком' && opp.LastStageUpdated__c.addDays(60) < datetime.now()) ||
            (opp.StageName == 'Заказ на производство оборудования' && opp.LastStageUpdated__c.addDays(60) < datetime.now())          
        ){
            may = true;         
        } 
        if(may) dynPageBlockButtons.childComponents.add(dynButtonSave);        
        dynPageBlockButtons.childComponents.add(dynButtonCancel);
        dynPageBlock.childComponents.add(dynPageBlockButtons);
        dynPageBlock.childComponents.add(dynPageMessages);
        if(!may)dynPageBlock.childComponents.add(dynPageMessage);
        if(may)dynPageBlockSection.childComponents.add(dynText);
        dynPageBlock.childComponents.add(dynPageBlockSection);        
        return dynPageBlock;
    }
    
    public class StageException extends Exception {}
    
    public PageReference saveLong() {
        PageReference redirectPage;
        Opportunity opp_stage = opp;
        try{
            if(opp.needProlongationText__c == NULL || opp.needProlongationText__c == '') throw new StageException('Необходимо заполнить причину продления.');
        } catch(StageException e) {
            ApexPages.addMessages(e);
            return null;
        }
        opp_stage.needProlongation__c = true;
        update opp_stage;
        try {                
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setObjectId(opp.id);
            req1.setComments(opp.needProlongationText__c);
            Approval.ProcessResult result = Approval.process(req1);   
            redirectPage = stdController.view();            
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        return redirectPage;
    }
}