unpackaged/main/default/objects/Opportunity/fields/AuctionDateDesign__c.field-meta.xml
<CustomField>
    <fullName>AuctionDateDesign__c</fullName>
    <label>Дата конкурса на проектирование</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник ответственный за Проект</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Возможности</relationshipLabel>
    <relationshipName>mExE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>Пользователь ТИОН</label>
    <nameField>
        <label>ФИО</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Пользователи ТИОН</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Профиль пользователя</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCustom</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestScheduledDays.cls
@isTest(SeeAllData=true)
private class TestScheduledDays {
    
    static testmethod void test() {
        Test.startTest();
        
        User__c UT = new User__c(User__c = UserInfo.getUserId(), Name = 'tester');
        insert UT;
        
        Opportunity opp = new Opportunity(UserTION__c = UT.id);
        opp.Name='Test opp';
        opp.StageName='Подбор оборудования';
        opp.CloseDate=Date.today();
        opp.AuctionDateDesign__c = Date.today();
        opp.RecordTypeId='012b0000000L3bI';
        insert opp;
        
        
    
        
        scheduledDays.scheduleIt();
        String jobID = System.schedule(
            '_unittest_scheduled_: 001',
            '0 0 * * * ? *',
            new scheduledDays()
        );
        
        Test.stopTest();
    
    }     
}