unpackaged/main/default/objects/Opportunity/fields/DaysFromLastStageUpdated__c.field-meta.xml
<CustomField>
    <fullName>DaysFromLastStageUpdated__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Дней с последнего изменения этапа</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LastStageUpdated__c.field-meta.xml
<CustomField>
    <fullName>LastStageUpdated__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Временная метка последнего обновления этапа, изменяется автоматически триггером.</description>
    <label>Последнее обновление этапа</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/UpdatedLast__c.field-meta.xml
<CustomField>
    <fullName>UpdatedLast__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <label>UpdatedLast</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/scheduledDays.cls
global class scheduledDays implements Schedulable {
     

    global static String scheduleIt() {
        String ret = 'ok';
        try{
            for(Integer j=0; j< 60; j = j + 2){
        		System.schedule('Last State Days Update ' + String.valueOf(j) + '', '0 ' + String.valueOf(j) + ' * * * ? *', new scheduledDays());
            }
        }
        catch(System.DMLException e){
        	ret = String.valueOf(e);   
        }   
        return ret;
    }
     
    global void execute(SchedulableContext sc) {
    	List<Opportunity> opp = [SELECT id, LastStageUpdated__c, DaysFromLastStageUpdated__c, UpdatedLast__c, StageName FROM Opportunity WHERE UpdatedLast__c != TODAY];
        Integer i = 0;
        if(!opp.isEmpty()) for(Integer j=0; j< opp.size() && i < 45; j++){
            if(opp[j].StageName != 'Закрыто как не профиль' && opp[j].StageName != 'Закрыто как провал'){
                if(opp[j].LastStageUpdated__c == NULL){
                    OpportunityHistory oh = [SELECT id, CreatedDate, StageName FROM OpportunityHistory WHERE OpportunityId = :opp[j].id AND isDeleted = false ORDER BY CreatedDate DESC LIMIT 1];
                    opp[j].LastStageUpdated__c = oh.CreatedDate;
                } 
                Integer days = Integer.valueOf((datetime.now().getTime() - opp[j].LastStageUpdated__c.getTime())/(60*60*24*1000));
                opp[j].DaysFromLastStageUpdated__c = days;
                opp[j].UpdatedLast__c = datetime.now();
                try{
                    update opp[j];
                }
                catch(System.DMLException e){}
                i++;
            }
        }
        
    }
}