unpackaged/main/default/objects/Opportunity/fields/HiddenStageNameBeforeApprovalStarts__c.field-meta.xml
<CustomField>
    <fullName>HiddenStageNameBeforeApprovalStarts__c</fullName>
    <label>Этап до процесса утверждения</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/isClosingRejected__c.field-meta.xml
<CustomField>
    <fullName>isClosingRejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Закрытие проекта отклонено</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник ответственный за Проект</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Возможности</relationshipLabel>
    <relationshipName>mExE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>Пользователь ТИОН</label>
    <nameField>
        <label>ФИО</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Пользователи ТИОН</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Профиль пользователя</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCustom</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestApprovingProjectForClosing.cls
@isTest(seeAllData=true)
private class TestApprovingProjectForClosing {

    static testMethod void myUnitTest() {
        
        User__c UT = new User__c(User__c = UserInfo.getUserId(), Name = 'tester');
        insert UT;
        
        Opportunity opp = new Opportunity(UserTION__c = UT.id);
        opp.Name='Test opp';
        opp.StageName='Закрыто как не профиль';
        opp.CloseDate=Date.today();
        insert opp;
        update opp;
        
        Opportunity opp1 = new Opportunity(UserTION__c = UT.id);
        opp1.Name='Test opp';
        opp1.StageName='Закрыто как провал';
        opp1.CloseDate=Date.today();
        insert opp1;
        update opp1;

        Opportunity opp2 = new Opportunity(UserTION__c = UT.id);
        opp2.Name='Test opp';
        opp2.StageName='Закрыто как не профиль';
        opp2.CloseDate=Date.today();
        insert opp2;
        opp2.isClosingRejected__c = true;
        opp2.HiddenStageNameBeforeApprovalStarts__c = 'Переговоры с проектировщиком';
        update opp2;
        
        
        
        Opportunity opp3 = new Opportunity(UserTION__c = UT.id);
        opp3.Name='Test opp';
        opp3.StageName='Закрыто и реализовано';
        opp3.CloseDate=Date.today();
        insert opp3;
        update opp3;
        
       
    }
}