unpackaged/main/default/objects/Opportunity/fields/ProjectRegion__c.field-meta.xml
<CustomField>
    <fullName>ProjectRegion__c</fullName>
    <label>Регион проекта</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Москва</fullName>
            </value>
            <value>
                <fullName>Санкт-Петербург</fullName>
            </value>
            <value>
                <fullName>Республика Адыгея</fullName>
            </value>
            <value>
                <fullName>Республика Алтай</fullName>
            </value>
            <value>
                <fullName>Республика Башкортостан</fullName>
            </value>
            <value>
                <fullName>Республика Бурятия</fullName>
            </value>
            <value>
                <fullName>Республика Дагестан</fullName>
            </value>
            <value>
                <fullName>Республика Ингушетия</fullName>
            </value>
            <value>
                <fullName>Республика Кабардино-Балкарская</fullName>
            </value>
            <value>
                <fullName>Республика Калмыкия</fullName>
            </value>
            <value>
                <fullName>Республика Карачаево-Черкесская</fullName>
            </value>
            <value>
                <fullName>Республика Карелия</fullName>
            </value>
            <value>
                <fullName>Республика Коми</fullName>
            </value>
            <value>
                <fullName>Республика Марий Эл</fullName>
            </value>
            <value>
                <fullName>Республика Мордовия</fullName>
            </value>
            <value>
                <fullName>Республика Саха (Якутия)</fullName>
            </value>
            <value>
                <fullName>Республика Северная Осетия — Алания</fullName>
            </value>
            <value>
                <fullName>Республика Татарстан</fullName>
            </value>
            <value>
                <fullName>Республика Тыва (Тува)</fullName>
            </value>
            <value>
                <fullName>Республика Удмуртская</fullName>
            </value>
            <value>
                <fullName>Республика Хакасия</fullName>
            </value>
            <value>
                <fullName>Республика Чеченская</fullName>
            </value>
            <value>
                <fullName>Республика Чувашская</fullName>
            </value>
            <value>
                <fullName>Алтайский край</fullName>
            </value>
            <value>
                <fullName>Забайкальский край</fullName>
            </value>
            <value>
                <fullName>Камчатский край</fullName>
            </value>
            <value>
                <fullName>Краснодарский край</fullName>
            </value>
            <value>
                <fullName>Красноярский край</fullName>
            </value>
            <value>
                <fullName>Пермский край</fullName>
            </value>
            <value>
                <fullName>Приморский край</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Сотрудник ответственный за Проект</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Возможности</relationshipLabel>
    <relationshipName>mExE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroup__c/OpportunityGroup__c.object-meta.xml
<CustomObject>
    <label>Группа проекта</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Идентификатор</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Группа проекта</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OpportunityGroup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Возможность</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>OppGroup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroup__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <label>Роль</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Менеджер по продажам</fullName>
            </value>
            <value>
                <fullName>Региональный менеджер по продажам</fullName>
            </value>
            <value>
                <fullName>Руководитель отдела продаж</fullName>
            </value>
            <value>
                <fullName>Руководитель сервисной службы</fullName>
            </value>
            <value>
                <fullName>Сервисный инженер</fullName>
            </value>
            <value>
                <fullName>Проектировщик</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityGroup__c/fields/UserTION__c.field-meta.xml
<CustomField>
    <fullName>UserTION__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Сотрудник</label>
    <referenceTo>User__c</referenceTo>
    <relationshipName>UserTION</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/OpportunitySearch.cls
public class OpportunitySearch{
    public OpportunityGroup__c oppGroup {set;get;}    
    public List<OppResult> opp_r = new List<OppResult>();
    
    public boolean renderResult = false;
    
    public OpportunitySearch() {
        oppGroup = new OpportunityGroup__c();
        setDefault();
    }  
    
    public boolean getrenderResult(){
    	return renderResult;    
    }
    
    public List<OppResult> getopp_r(){
    	return opp_r;
    }
    
    public void setDefault(){        
        sortBy = 'LastModifiedDate';
        sortDir = 'DESC';
    }
    
    public String sortBy { get; set; }
    public String sortDir { get; set; }
    
    public PageReference empty() { 
        return searchEngine(); 
    }
    
    public class OppResult {
        public ID id {get;set;}  
        public String name {get;set;}  
        public String ProjectRegion {get;set;}  
        public String Amount {get;set;}  
        public String StageName {get;set;}  
        public String url {get;set;}   
    }
    
    public PageReference searchOpp(){
        setDefault();
        return searchEngine();
    }
    
    public PageReference searchEngine() {        
		if(!opp_r.isEmpty()) opp_r.clear();          
        if(oppGroup.UserTION__c == NULL){        	   
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Не выбран пользователь.'));  
            renderResult = false;
            return NULL;
        }     
        List<OpportunityGroup__c> opp_g = NULL;
        String Role = '';
        if(oppGroup.UserRole__c != NULL) Role = ' AND UserRole__c = :UR';
        ID UT = oppGroup.UserTION__c;
        String UR = oppGroup.UserRole__c;
        String soql_query = 'SELECT Opportunity__r.id, Opportunity__r.name, Opportunity__r.ProjectRegion__c, Opportunity__r.Amount, Opportunity__r.StageName'+ 
                 ' FROM OpportunityGroup__c WHERE UserTION__c = :UT' + Role + ' ORDER BY Opportunity__r.' + sortBy + ' ' + sortDir;
        opp_g = Database.query(soql_query);
        if(opp_g.isEmpty()){        	   
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Ничего не найдено.'));  
            renderResult = false;
            return NULL;
        }      
        for (OpportunityGroup__c og : opp_g){
            OppResult ors = new OppResult();
            ors.id = og.Opportunity__r.id;
            ors.name = og.Opportunity__r.name;
            ors.ProjectRegion = og.Opportunity__r.ProjectRegion__c;
            ors.Amount = String.ValueOf(og.Opportunity__r.Amount);
            ors.StageName = og.Opportunity__r.StageName;
            ors.url = URL.getSalesforceBaseUrl().toExternalForm() + '/' + ors.id;
       		opp_r.add(ors);
        }
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Найдено: ' + String.valueOf(opp_r.size()) + ''));  
        PageReference pageRef = ApexPages.currentPage(); 
        //pageRef.setRedirect(true);
        renderResult = true;
        return NULL;
    }
    
}